liam-hq/liam

frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap, frontend/packages/db-structure/src/parser/sql/input/postgresql_schema1.in.sql, frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts, frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
Extract column comments in `postgres`
ref: in `schemarb`, https://github.com/liam-hq/liam/pull/156
=> Extract column comments in `postgres`

frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts, frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts, frontend/packages/db-structure/src/schema/dbStructure.ts, frontend/packages/db-structure/src/schema/index.ts
- **feat: Implement handling of one-to-one relationships based on unique indexes in PostgreSQL converter**
- **feat: Add cardinality validation to relationship schema**
=> feat: parse one to one relationships

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.module.css, frontend/packages/ui/src/styles/variables.css
I've set up web font of IBX Plex Mono.
https://fonts.google.com/specimen/IBM+Plex+Mono
=> feat: add `--code-font`

.github/workflows/vercel-deploy-erd-sample.yml, .github/workflows/vercel-deploy.yml, frontend/apps/erd-sample/package.json, frontend/apps/erd-sample/schema.rb
Update ERD sample with a larger real-world schema.
f0654b8  `Separate Vercel deploy workflow into two YAML files` solves https://github.com/liam-hq/liam/pull/171#discussion_r1872483760 .
* f0654b8 : refactor: Separate Vercel deploy workflow into two YAML files
* 2de4564 : refactor: Use `vars` (Actions variables) instead of `secrets`
* 0d9bc3b : Update ERD sample with a larger real-world schema
* **main change**
I manually checked vercel preview site. :)
N/A
=> Vercel deploy erd sample: larger schema.rb

frontend/packages/cli/src/App.tsx, frontend/packages/cli/vite.config.ts
For placing cli's output to subdirectories.
- Updated `fetch` calls in `App.tsx` to use relative paths (`./schema.json`) for consistent resource loading.
N/A
N/A
=> Update to relative paths

frontend/config/dependency_decisions.yml, frontend/docs/packages-license.md, frontend/packages/erd-core/package.json, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertElkEdgesToEdges.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertElkNodesToNodes.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertNodesToElkNodes.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/getElkLayout.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/index.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts, frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts, frontend/pnpm-lock.yaml
- I have implemented Elk.js
- I applied automatic layout to a group of TableNodes using the ELK Force layout algorithm
- I expanded the zoomable range to 0.25-2 times
=> feat: Add useAutoLayout

frontend/docs/packages-license.md, frontend/packages/db-structure/src/index.ts, frontend/packages/erd-core/package.json, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/extractDBStructureForTable.test.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/extractDBStructureForTable.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx, frontend/pnpm-lock.yaml, frontend/turbo.json
I've implemented related tables viewer in table detail.
https://github.com/user-attachments/assets/d1b02e61-8172-491d-bef9-7ae197b0414c
=> feat: implement related tables

frontend/packages/db-structure/src/parser/schemarb/index.test.ts, frontend/packages/db-structure/src/parser/schemarb/parser.ts, frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts, frontend/packages/db-structure/src/parser/utils/defaultRelationshipName.ts, frontend/packages/db-structure/src/parser/utils/index.ts
- ref: https://github.com/liam-hq/liam/pull/193
=> fix: set default relationship name when key name is not found

frontend/packages/cli/CHANGELOG.md, frontend/packages/cli/package.json
=> Version Bump `@liam-hq/cli`

.github/workflows/vercel-deploy-erd-sample.yml, .github/workflows/vercel-deploy.yml, frontend/apps/erd-sample/package.json
Simplify checkout procedure in vercel-deploy-erd-sample.yml
* ce8230c : refactor: use https input url option instead of `git checkout`
* da89906 : refactor: apply `erd build --input [URL]` style
* c15cc0b : refactor: remove redundant `--token` argument from `vercel build` commands
=> Simplify checkout procedure in vercel-deploy-erd-sample.yml

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
I have modified the styles for TableNodes.
The following three styles have been changed.
https://github.com/liam-hq/liam/pull/206/commits/905da8b198904ad88eb66cbab79ed8e9a291d353 : add border-radius to the columnWrapper last-child
Before --> After
https://github.com/liam-hq/liam/pull/206/commits/126362cdf2fc17fb422c96c9d8aef6db3e7818fa : align column type names to the center
Before --> After
https://github.com/liam-hq/liam/pull/206/commits/6b5b799c3715d6cfdb954d6221a920bea69b4aa1 : adjust handle position
Before --> After
=> Fix table node styles(Align column types, adjust handle position, and round column corners in tables)

frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
As there was code to extract the relationship in each of ALTER TABLE and CREATE TABLE, it has been made common.
=> refactor(postgres parser): refactor constraints node handling

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useFitViewWhenActiveTableChange.ts
https://github.com/user-attachments/assets/189b58c4-4fdb-49bd-8a31-e47970855e27
=> feat: adjust view when active table changed

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.module.css
Increased brightness of edge.
| ![Image](https://github.com/user-attachments/assets/5ad5b410-4a88-45b5-a5c2-2217acd68804) | ![Image](https://github.com/user-attachments/assets/e26503a5-a84e-492f-b7dc-ca3cd8d84dba) |
=> fix: change stroke of RelationshipEdge

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
Highlight source node cardinalities.
Highlighting target node cardinalities is going to be next PR.
=> Highlight source node cardinalities

frontend/packages/db-structure/src/parser/errors.ts, frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts, frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts, frontend/packages/db-structure/src/parser/sql/postgresql/index.ts, frontend/packages/db-structure/src/parser/sql/postgresql/parser.ts
- **refactor: Refactor SQL parser types to use ParseResult**
- **feat: Add UnexpectedTokenWarningError and enhance error handling in SQL processor**
- **refactor: Remove unnecessary null check for statements in SQL converter**
=> feat: show error when parse postgres schema

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
https://github.com/user-attachments/assets/a8cd03ca-81c2-4921-b0c1-19402475e75d
=> feat: move toolbar to ERDRenderer and disable toolbar in Related Tables

.changeset/gorgeous-ways-call.md, frontend/packages/cli/index.html, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/AppBar.tsx
Updated title and ERD view header title.
=> Updated title and ERD view header title

.changeset/spicy-jeans-whisper.md, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/HelpButton.tsx
I've implemented to access to documents.
=> feat: Add HelpButton functionality to open documentation and community forum links

frontend/.changeset/lemon-peaches-destroy.md, frontend/.changeset/lovely-papayas-hunt.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/ui/src/components/IconButton/IconButton.tsx
https://github.com/user-attachments/assets/0e8950f8-c038-4712-bdd9-30bf9efd5595
=> feat: Added the functionality to display only the selected table from TableDetail in the Main Pane

frontend/.changeset/few-socks-jam.md, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableCounter/TableCounter.tsx
https://github.com/user-attachments/assets/22c5a096-b5c6-4940-956a-70b8567e748a
=> feat: LeftPane now shows the number of tables currently being displayed

frontend/.changeset/empty-hotels-hug.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
=> fix: reword to `Open in main area`

.github/workflows/vercel-deploy-erd-sample.yml, frontend/apps/erd-sample/package.json, frontend/apps/erd-sample/scripts/update_dist_content.mjs
Added script to update dist content for Vercel ERD-sample deploy.
Prepared for future integration of internal analytics tool tags by adding the capability to inject custom content into the build process
=> feat: add script to update dist content for Vercel ERD-sample deploy

frontend/.changeset/afraid-gifts-push.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useUpdateNodeCardinalities.ts
When hiding node, cardinalities also should be hidden.
Future work:
* case of using hidden tables function from Related Tables
* source cardinalities
* hide cardinality immediately
https://github.com/user-attachments/assets/5069d779-94f2-4034-9da5-fb8819647984
=> Refactor hidden node handles

frontend/.changeset/curvy-glasses-swim.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumnList.tsx, frontend/packages/erd-core/src/components/ERDRenderer/columnHandleId.ts, frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
- **refactor: Refactor handle ID generation for table columns to use a dedicated function**
- **refactor: Simplify TableColumn component by passing handleId as a prop and removing unnecessary highlightedHandles logic**
- **maintenance: add changeset**
=> refactor: Move the calculation to TableColumnList and TableColumn only displays the props

frontend/.changeset/pink-otters-happen.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
It is quite minimal, I have been modified to match the way React Flow is implemented.
=> refactor: The behavior of TableNode when clicked is unified to be handled by ERDContent

frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
=> :children_crossing: Sort table nodes by name in LeftPane component

frontend/apps/erd-sample/scripts/update_dist_content.mjs
erd-sample: Add meta tag `robots` to prevent search engines from indexing
see preview: https://liam-erd-sample-fke6r5p72-route-06-core.vercel.app
html source:
=> :mag: erd-sample: Add meta tag `robots` to prevent search engines from indexing

frontend/.changeset/tricky-comics-raise.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts
The uses were the same, so I will unify them.
=> refactor: Integrated `isRelated` into `isHighlighted`

frontend/.changeset/pink-drinks-applaud.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts, frontend/packages/erd-core/vitest.config.ts
Cutting out handling of active tables into functions and adding tests.
=> refactor: Refactoring and testing of highlights on active tables

frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
Add click log for table detail close.
https://github.com/user-attachments/assets/4fe0464b-478a-46c0-9771-35b5dabb3867
=> 📈 : Add click log for table detail close

frontend/.changeset/young-moles-exercise.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts
- https://github.com/liam-hq/liam/pull/317
I noticed a problem during QA and have fixed it. 🙏🏻
=> fix: Fixed failure to highlight parent table

frontend/.changeset/hungry-dots-help.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
=> Show column types in table nodes when the table is highlighted

frontend/.changeset/few-apples-exercise.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/features/gtm/utils/repositionTableLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/selectTableLogEvent.ts
add type for reposition table logging
(updated)
https://github.com/user-attachments/assets/8b279051-d36b-469b-b926-ca9341837fe7
=> :chart_with_upwards_trend: add type for reposition table logging

frontend/.changeset/tricky-windows-smash.md, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/AppBar.tsx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/ReleaseNoteButton/ReleaseNoteButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/Toolbar.tsx
* Disable unimplemented features
* View control button
* Export button
* Add Link to Release button
* https://github.com/liam-hq/liam/releases
=> maintenance: Add GitHub Release Link and Disable some features

frontend/.changeset/brave-guests-explode.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts, frontend/packages/erd-core/src/components/ERDRenderer/constants.ts, frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
close: https://github.com/liam-hq/liam/issues/335
=> 🐛: Highlight source cardinality with multi-foreign keys

frontend/.changeset/mean-eels-suffer.md, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/CopyLinkButton/CopyLinkButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/FitviewButton/FitviewButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ZoomControls/ZoomControls.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx, frontend/packages/erd-core/src/features/gtm/utils/clickLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/openRelatedTablesLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/repositionTableLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/selectTableLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/toggleLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/toolbarActionLogEvent.ts
Add ``appEnv`` parameter to log event functions and components.
I've tested all clicks and other interactions.
=> 📈 add appEnv parameter to logging events for environment tracking.

frontend/.changeset/slimy-toys-yell.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
Highlighting was not handled during initial display, so it has been added.
https://github.com/user-attachments/assets/496c3af1-4c06-4d22-82bf-5daa7ddc41c0
~Merge after the following PR merged.~
- https://github.com/liam-hq/liam/pull/342
=> fix: Fixed problem with TableNode not being highlighted when opened from URL with query parameter

frontend/.changeset/orange-books-join.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
=> ⚒️　Fixing the toolbar display bug

.changeset/curvy-carrots-eat.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
https://github.com/user-attachments/assets/08725889-1154-41f5-98c5-c22203de131e
=> 💄 feat: Sticky positioning for related tables in TableDetail

frontend/apps/docs/next.config.mjs
In order to allow the service site to access the ``frontend/apps/docs`` directory in this repository, I've configured an ``assetPrefix``.
=> Set the assetPrefix to be accessible from Service Site

.github/workflows/vercel-deploy.yml, frontend/apps/erd-web/next.config.ts, frontend/apps/erd-web/package.json, frontend/apps/erd-web/tsconfig.json, pnpm-lock.yaml
Add deploy workflow for Liam ERD Web.
=> 🚀: Add ERD web project to Vercel deployment workflow

.changeset/twenty-terms-visit.md, frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx, frontend/apps/erd-web/next.config.ts, frontend/packages/cli/src/App.tsx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/ReleaseVersion.tsx, frontend/packages/erd-core/src/schemas/cliVersion/schemas.ts
Add commit hash and release data  for ERD Web.
`cliVersion` will be refactored to more reasonable in next PR.
sample url for checking:
https://liam-erd-c635e64zt-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/companionstudio/islay-integration/refs/heads/master/db/structure.sql
=> ✨ : Add commit hash and release date indicator

.changeset/nine-snakes-beg.md, frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx, frontend/packages/cli/src/App.tsx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/CopyLinkButton/CopyLinkButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/ReleaseVersion.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/FitviewButton/FitviewButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ZoomControls/ZoomControls.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx, frontend/packages/erd-core/src/schemas/cliVersion/schemas.ts
* use discriminated union for cliVersion
* fix ReleaseVersion display for CLI
* disable GTM logging for ERD Web
* In my understanding, GTM logging is just for internal testing
* we need to discuss logging way to monitor user actions for production🤔
=> Fix and Refactor cliVersion

.changeset/large-dolphins-grow.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
- resolve: https://github.com/liam-hq/liam/issues/348
https://github.com/user-attachments/assets/c4009ff1-8e20-49ca-b868-90b6050753fd
=> :bug: No focus when Active table in Related Tables

.changeset/five-foxes-work.md, frontend/apps/docs/content/docs/supported-format.mdx, frontend/apps/docs/content/docs/url-based-access.mdx, frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx, frontend/apps/erd-web/app/types.ts, frontend/packages/db-structure/src/parser.ts, frontend/packages/db-structure/src/parser/index.ts, frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.test.ts, frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.ts, frontend/packages/db-structure/src/parser/supportedFormat/index.ts, frontend/packages/db-structure/src/parser/supportedFormat/schema.ts
Added the features to infer format identification and specify it in query parameters!
https://liam-erd-ctjuxynb7-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/mastodon/mastodon/refs/heads/main/db/schema.rb
https://liam-erd-ctjuxynb7-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/ekylibre/ekylibre/refs/heads/main/db/structure.sql
=> ✨ detect format

.changeset/clever-cherries-tan.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
I've removed the ``min-width`` constraint on the toolbarWrapper to eliminate the extraneous margin. As a result, the toolbarWrapper animation has been slightly modified.
| Before  | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/a855275e-e38e-4a22-8c97-072bbcf60050"> | <video src="https://github.com/user-attachments/assets/3ab03f8f-2e2c-4ed6-8a1c-8c0700351e6f">  |
=> 🐛 Fix unnecessary whitespace generation

.changeset/yellow-jobs-melt.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/usePopStateListener.ts, frontend/packages/erd-core/src/stores/userEditing/actions.ts, frontend/packages/erd-core/src/stores/userEditing/store.ts
Enable browser back and forward for active table:
https://github.com/user-attachments/assets/23b34648-37c5-478a-88c7-f56366129a48
=> ✨ feat: Enable browser back and forward for active table

frontend/apps/erd-web/.env.production, frontend/apps/erd-web/.gitignore, frontend/apps/erd-web/next.config.ts, frontend/apps/erd-web/public/robots.txt
- **:wrench: Add assetPrefix configuration to make it accessible from the service site**
- ref: https://github.com/liam-hq/liam/pull/369
- **:wrench: Add robots.txt to disallow all web crawlers**
- ref: https://github.com/liam-hq/liam/pull/392
- **:recycle: remove unnecessary .keep file**
- **:wrench: Add .env.production file with ASSET_PREFIX configuration**
=> :wrench: to make accesible from service site

frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
Add conversion from `github.com` to `raw.githubusercontent.com`.
Try:
https://liam-erd-kkbljftwm-route-06-core.vercel.app/erd/p/github.com/ekylibre/ekylibre/blob/main/db/structure.sql
=> ✨ feat: Add conversion from github.com to raw.githubusercontent.com

.changeset/fuzzy-weeks-beg.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
follow up https://github.com/liam-hq/liam/pull/435 .
`ERDRenderer` was also used by cli package. 🙏  https://github.com/liam-hq/liam/blob/f575795ac23844fccf5f89226e5336207cc32c23/frontend/packages/cli/src/App.tsx#L50 
https://liam-erd-sample-fx2yr05sz-route-06-core.vercel.app/ shows contents.
=> 🐛 Fix argument type of errors

frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap, frontend/packages/db-structure/src/parser/schemarb/input/schema1.in.rb
I added the amount of information in the schema file used in the test.
=> 🔧 update fixture

frontend/apps/docs/content/docs/parser/index.mdx, frontend/apps/docs/content/docs/parser/troubleshooting.mdx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/HelpButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay.tsx
This PR focuses on styling. Please review it from that perspective 🙏 .
💄 Style to ErrorDisplay component
local: http://localhost:3001/erd/p/raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
preview: https://liam-erd-41czdfe8k-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
No changeset added.
=> 💄 Style to ErrorDisplay component

.changeset/strong-weeks-report.md, docs/packages-license.md, frontend/packages/db-structure/package.json, frontend/packages/db-structure/src/parser/prisma/index.test.ts, frontend/packages/db-structure/src/parser/prisma/index.ts, frontend/packages/db-structure/src/parser/prisma/parser.ts, pnpm-lock.yaml
Introduce `schema.prisma` parser by using `DMMF`.
DMMF is an AST (abstract syntax tree) of the datamodel in the form of JSON.
ref: https://github.com/prisma/prisma/blob/main/ARCHITECTURE.md#the-dmmf-or-data-model-meta-format
1. **Official Support**: DMMF is part of Prisma's package, ensuring reliability and up-to-date compatibility with Prisma features.
2. **Comprehensive Parsing**: It provides detailed parsing of models, fields, and relationships, surpassing JavaScript parsers and custom parsers (e.g. `PEG.js`) that aren't designed for Prisma's syntax.
3. **Ease of Use**: DMMF abstracts complexity, making it easier to integrate than custom parsers, which require significant setup and maintenance.
DMMF is chosen for its reliability, comprehensive parsing, and ease of integration, offering …
=> ✨ Introduce prisma parser

frontend/packages/db-structure/src/parser/prisma/index.test.ts
=> ✅ Add nullable test for Prisma

frontend/apps/docs/content/docs/web.mdx, frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.ts
I made two minor fixes:
* d6797474 : docs: Fix a path
* c8cb0163 : add a comment for a .ts file which is referred from docs
=> docs: Fix a path

.changeset/new-guests-lay.md, frontend/apps/erd-web/next.config.ts, frontend/packages/cli/package.json, frontend/packages/cli/rollup.config.js, frontend/packages/db-structure/src/parser/index.ts, frontend/packages/db-structure/src/parser/prisma/parser.ts, frontend/packages/db-structure/src/parser/supportedFormat/schema.ts, pnpm-lock.yaml
Support for Prisma format in parser.
`@prisma/internals` is CommonJS, we had some problems with `cli` and `erd-web`.
This PR contains workarounds for those problems.
=> ✨ Add support for Prisma format in parser

.changeset/slow-squids-do.md, frontend/packages/cli/src/cli/initCommand/index.ts
✨ initCommand: Add `Drizzle` intruction support and `Other` option
* 64e936e8 : Drizzle intruction support
* 211703a5 : Add preliminary support message for other databases in initCommand
* 60881ef8 : Add .changeset
```mermaid
flowchart TB
A((Start)) --> B{dbOrOrm?}
B -- "PostgreSQL" --> C[Ask: Use .sql from pg_dump?]
C -- "Yes" --> D["Ask for dump file path (default: dump.sql)"]
C -- "No" --> E["Show message: Please run pg_dump --schema-only ... "]
B -- "Rails/Prisma" --> F["Ask for schema file path (default: db/schema.rb , prisma/schema.prisma)"]
D --> G{Add GitHub Actions?}
E --> G
F --> G
G -- "Yes" --> H[Generate GitHub Actions .github/workflows/erd.yml]
G -- "No" --> I[Skip GitHub Actions Workflow Generation]
H & I --> J[Show docs link Print]
J --> K((End))
```
```mermaid
flowchart …
```
=> ✨ initCommand: Add `Drizzle` intruction support and `Other` option

frontend/packages/cli/vite-plugins/remove-import-wasi.ts, frontend/packages/cli/vite.config.ts
=> Fix typo `renameImportWasi`-> `removeImportWasi`

frontend/packages/cli/src/cli/initCommand/index.ts
follow-up https://github.com/liam-hq/liam/pull/471#discussion_r1918086058
```mermaid
flowchart TB
A((Start)) --> B{dbOrOrm?}
B -- "PostgreSQL" --> C[Ask: Use .sql from pg_dump?]
C -- "Yes" --> D["Ask for dump file path (default: dump.sql)"]
C -- "No" --> E["Show message: Please run pg_dump --schema-only ... "]
B -- "Rails/Prisma" --> F["Ask for schema file path (default: db/schema.rb , prisma/schema.prisma)"]
B -- "Drizzle" --> L["drizzle-specific intruction. For Drizzle, please run your DB migrations, then use 'pg_dump --schema-only' to generate a dump file. You can then use it with --format postgresql."]
B -- "Others" --> M["💔 For other DBs, Sorry we don't support them yet 💔 Visit discussion"]
D --> G{Add GitHub Actions?}
E --> G
F --> G
L --> G
G -- "Yes" --> H[Generate GitHub Actions …
```
=> tweak: initCommand: Confirm `Using PostgreSQL?` after drizzle chosen

frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
erd-web: Add `Fetching content` log
=> erd-web: Add `Fetching content` log

CONTRIBUTING.md
I've updated our CONTRIBUTING guidelines. 
I've added instructions on creating ``changesets`` and introduced ``gitmoji``.
Preview: https://github.com/liam-hq/liam/blob/a7d56604735be18daa56a0be6bf248d21aff4227/CONTRIBUTING.md#how-to-submit-a-pull-request
=> 📝 Update CONTRIBUTING.md to enhance changeset message guidelines

.changeset/violet-tools-boil.md, frontend/packages/cli/src/cli/actionRunner.ts, frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts, frontend/packages/cli/src/cli/initCommand/index.ts, frontend/packages/cli/src/cli/smoke.test.ts, frontend/packages/cli/src/cli/urls.ts
🚸  Improve success/error message at `erd build`
- **Enhanced CLI messaging:**  
- Improved the success/error message when generating an ERD.  
- Included a troubleshooting URL when errors occur in `actionRunner.ts`.  
- **Centralized URL management:**  
- Added a new `urls.ts` file to store commonly used URLs (`DocsUrl`, `TroubleshootingUrl`, etc.).  
- Replaced hardcoded URLs in CLI messages with variables from `urls.ts`.  
- **Updated smoke tests:**  
- Adjusted expected CLI output to match the new ERD generation success message.
=> 🚸  Improve success/error message at `erd build`

CONTRIBUTING.md
Just a small correction to https://github.com/liam-hq/liam/pull/494.
* Before
* https://github.com/liam-hq/liam/blob/1b18bf18cd4ce733dabbfc41fa933088909ce4ac/CONTRIBUTING.md
* After
* https://github.com/liam-hq/liam/blob/7c1ea54bc75aeee79aade1d4c6dc475dbbad74da/CONTRIBUTING.md
=> 📝 Don't render text emoji in CONTRIBUTING.md

frontend/apps/docs/content/docs/web.mdx
📝 Updated docs/web.mdx
- please preview this page: https://liam-docs-2eplg8axx-route-06-core.vercel.app/docs/web
- the animation gif is work in progress.
=> 📝 Update docs/web.mdx

frontend/apps/docs/content/docs/web.mdx
- related: https://github.com/liam-hq/liam/pull/503
Replace the GIF image with a new one output by Screen Studio.
preview: https://liam-docs-aojgi8qj0-route-06-core.vercel.app/docs/web
=> docs: Update animation gif path in web.mdx

frontend/apps/docs/content/docs/cli/index.mdx
Write Liam ERD CLI document in details.
The sections are `Quick Start` and `Manual Setup`.
=> 📝 Enhance documentation for Liam ERD CLI

frontend/apps/docs/content/docs/index.mdx
As the galaxy page is not ready for launch, we have temporarily removed the related navigation.
Furthermore, there were no other navigation paths to the galaxy page.
=> 📝 Remove Explore Diagrams section from documentation

.changeset/fresh-beers-invite.md, frontend/packages/db-structure/src/parser/prisma/index.test.ts, frontend/packages/db-structure/src/parser/prisma/parser.ts
Fixed Prisma relationship direction.
|before|after|
|--|--|
|<img width="398" alt="image" src="https://github.com/user-attachments/assets/b36d2f3b-a271-48c8-925b-355335422756" />|<img width="398" alt="image" src="https://github.com/user-attachments/assets/46412205-b8a3-48bc-a652-c59460966288" />|
=> 🐛 Fix prisma relationship direction

frontend/apps/docs/content/docs/cli/ci-cd.mdx
📝 Update docs/cli/ci-cd.mdx
preview: https://liam-docs-h8vdfew31-route-06-core.vercel.app/docs/cli/ci-cd
=> 📝 Update docs/cli/ci-cd.mdx

frontend/apps/docs/.env.production, frontend/apps/docs/app/docs/.env.development, frontend/apps/docs/app/docs/[[...slug]]/page.tsx
In [the previous PR](https://github.com/liam-hq/liam/pull/514), the image path for the docs was not set up correctly, so I've added it now.
Although I've updated the paths in this PR, the preview environment continues to use the production paths.💭
preview: https://liam-docs-3w1g3rdn9-route-06-core.vercel.app/docs
=> 🐛 Add environment variable for base URL and update metadata generation

.changeset/sharp-mirrors-reflect.md, frontend/packages/db-structure/src/parser/prisma/index.test.ts, frontend/packages/db-structure/src/parser/prisma/parser.ts
Support Prisma relationship cardinality.
many-to-many will be handled with other PR.
https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations
=> ✨ Support Prisma relationship cardinality

frontend/apps/docs/content/docs/parser/supported-formats/index.mdx
- related: https://github.com/liam-hq/liam/issues/506
I changed the prisma paraser to an in-progress status 🏃🏻‍♂️
=> 📝 Update Prisma support status to indicate ongoing development

frontend/apps/docs/content/docs/index.mdx
📝 docs: simplify explanation for public project setup  &&  remove `<button>Generate</button>` 
preview: https://liam-docs-9nhmm36px-route-06-core.vercel.app/docs
=> 📝 docs: simplify explanation for public project setup &&  remove `<button>Generate</button>` 

frontend/packages/db-structure/src/parser/prisma/index.test.ts
Refactor: Extract Prisma schema header handling into a helper function 
- https://github.com/liam-hq/liam/pull/523/files#r1924489437
=> ♻️  Refactor: Extract Prisma schema header handling into a helper function 

.changeset/gold-doors-jog.md
=> 🎉 chore: bump minor version for public announcement

frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx, frontend/packages/erd-core/src/components/ERDRenderer/AppBar/CopyLinkButton/CopyLinkButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/FitviewButton/FitviewButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ZoomControls/ZoomControls.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx, frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx, frontend/packages/erd-core/src/features/gtm/utils/clickLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/openRelatedTablesLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/repositionTableLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/selectTableLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/toggleLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/toolbarActionLogEvent.ts, frontend/packages/erd-core/src/features/gtm/utils/types.ts, frontend/packages/erd-core/src/schemas/version/schemas.ts
Refactored to send tags for ERD Web.
I've confirmed all tags are delivered:
=> 📈 Refactor to send tags for ERD Web

frontend/apps/docs/content/docs/cli/ci-cd.mdx
preview: https://liam-docs-q12li259w-route-06-core.vercel.app/docs/cli/ci-cd
Tiny fix.
fix nested `<p>` tags issue in Callout component at .mdx file.
before:
after:
=> apps/docs: Fix nested `<p>` tags issue in Callout component at .mdx file

frontend/apps/docs/components/Banner/Banner.tsx
The link might be on the same domain, but it's likely a different application than `docs`, so we don't use Link.
https://liambx.com/docs
current error:
=> 🐛 apps/docs: Fix RSC payload failure

frontend/apps/docs/content/docs/ui-features/sharing-and-query-params.mdx
preview: https://liam-docs-93gz1v7lh-route-06-core.vercel.app/docs/ui-features/sharing-and-query-params
=> 📝 Enhance sharing and query parameters documentation

frontend/apps/docs/components/Tabs/Tabs.tsx
I added margins to the tab components to improve readability.🙏
=> 💄 Add margin-bottom to Tabs component for improved layout

frontend/apps/docs/content/docs/parser/supported-formats/rails.mdx
- Updated docs/parser/supported-formats/rails.mdx
=> 📝 Update docs/parser/supported-formats/rails.mdx

frontend/apps/docs/content/docs/parser/supported-formats/prisma.mdx
📝 Update docs/parser/supported-formats/prisma.mdx
=> 📝 Update docs/parser/supported-formats/prisma.mdx

docs/packages-license.md, frontend/apps/docs/.env.development, frontend/apps/docs/.env.production, frontend/apps/docs/app/global.css, frontend/apps/docs/app/layout.tsx, frontend/apps/docs/lib/gtm/GTMConsent.tsx, frontend/apps/docs/lib/gtm/GtagScript.tsx, frontend/apps/docs/lib/gtm/constants.ts, frontend/apps/docs/lib/gtm/index.ts, frontend/apps/docs/lib/gtm/updateConsent.ts, frontend/apps/docs/package.json, frontend/packages/ui/src/components/CookieConsent/CookieConsent.module.css, frontend/packages/ui/src/components/CookieConsent/CookieConsent.tsx, frontend/packages/ui/src/components/CookieConsent/index.ts, frontend/packages/ui/src/components/Drawer/Drawer.tsx, frontend/packages/ui/src/components/Toast/Toast.tsx, frontend/packages/ui/src/components/index.ts, pnpm-lock.yaml
I enabled GA4 tracking with GTM on the document site.
Also, I added a cookie consent popup and made it so that tracking is only done when the user agrees to this popup.
| initial / denied | accepted |
| ![スクリーンショット 2025-01-24 18 18 18](https://github.com/user-attachments/assets/b8ed28c6-232a-453e-ad2c-1b3d72364905) | ![スクリーンショット 2025-01-24 18 19 35](https://github.com/user-attachments/assets/265c5e33-fcf8-4560-9cb8-343ff1987744) | 
N/A
- [➕ Add new dependencies for third-party integration](https://github.com/liam-hq/liam/pull/562/commits/0d36fcb4b289db1a4c1dfd55fc8cf63cc63a4f29)
- Added the dependencies needed for implementation.
- [✨ Add Cookie Consent component with styles and functionality](https://github.com/liam-hq/liam/pull/562/commits/27ad12d02d084c2222067154eb66 …
=> ✨ Add Cookie Consent functionality and Google Tag Manager integration

frontend/apps/docs/content/docs/parser/supported-formats/rails.mdx
This PR fixes typo: `ruby/prisma` -> `ruby/prism`
=> 📝 Fix typo

.changeset/two-llamas-fail.md, docs/packages-license.md, frontend/packages/db-structure/.gitignore, frontend/packages/db-structure/package.json, frontend/packages/db-structure/scripts/tblsJsonSchemaToZod.mjs, frontend/packages/db-structure/src/parser/tbls/input/schema.json, frontend/packages/db-structure/src/parser/tbls/schema.generated.test.ts, pnpm-lock.yaml
- Add JSON Schema to Zod generation for tbls schema
- Add Test to parse correctly `schema.json`
- including: https://github.com/k1LoW/tbls/blob/v1.81.0/spec/tbls.schema.json_schema.json
=> ✨ Add JSON Schema to Zod generation for tbls schema

frontend/apps/docs/content/docs/parser/supported-formats/rails.mdx
> [!WARNING]
> we should merge https://github.com/liam-hq/liam-erd-samples/pull/3 first
📝 docs: Add sample workflow link for rails-add-association-foreign-key
preview : https://liam-docs-gxcwswf2v-route-06-core.vercel.app/docs/parser/supported-formats/rails
ref. https://github.com/liam-hq/liam-erd-samples/pull/3
=> 📝 docs: Add sample workflow link for rails-add-association-foreign-key

.syncpackrc, frontend/packages/cli/package.json
=> 🔧 Update cli package.json

frontend/apps/docs/app/layout.tsx
Passing `appEnv` to Google Tag Manager allows for reliable behavioral log tracking across all environments.
N/A
N/A
N/A
N/A
=> 📈 Enable GTM tracking in all environments

.changeset/five-planets-confess.md, frontend/packages/db-structure/src/parser/tbls/index.test.ts, frontend/packages/db-structure/src/parser/tbls/parser.ts
Support unique column constraints (only single column not multi column)
=> ✨ Add support for unique column constraints in tbls parser

frontend/apps/docs/content/docs/parser/supported-formats/index.mdx, frontend/apps/docs/content/docs/parser/supported-formats/tbls.mdx
- **📝 Add tbls documentation and update supported formats**
- **🔧 Add Prisma format identifier in supported formats table**
=> 📝 docs for tbls

frontend/apps/docs/content/docs/parser/supported-formats/index.mdx
- related: https://github.com/liam-hq/liam/issues/506
- related: https://github.com/liam-hq/liam/pull/591#discussion_r1931483539
prisma support clearly stated in the manual!
=> 📝 Change supported status for prisma

.cursorrules
A file has been added to allow the user to set custom instructions for using cursor as an editor.
I have added it with reference to https://github.com/PatrickJS/awesome-cursorrules, but you may continue to modify it as you see fit.
ref: https://docs.cursor.com/context/rules-for-ai#cursorrules
=> 🔧 Add Cursor AI development rules configuration file

frontend/packages/db-structure/src/parser/tbls/index.test.ts
Added tests for non-unique and unique indices in tbls parser.
The implementation has already done in https://github.com/liam-hq/liam/pull/577.
=> ✅ Add tests for non-unique and unique indices in tbls parser

frontend/packages/db-structure/src/parser/tbls/index.test.ts
I removed the necessary changes while resolving conflict 🙏
=> ✅ Fix tbls index testcase

frontend/packages/db-structure/src/parser/tbls/index.test.ts, frontend/packages/db-structure/src/parser/tbls/parser.ts
Support for foreign key actions in tbls parser.
No changeset because fk actions have not been displayed on frontend yet.
=> ✨ Support for foreign key actions in tbls parser

frontend/apps/docs/content/docs/parser/supported-formats/bigquery.mdx, frontend/apps/docs/content/docs/parser/supported-formats/index.mdx, frontend/apps/docs/content/docs/parser/supported-formats/sqlite.mdx
- **📝 Add SQLite documentation with tbls integration guide**
- **📝 Add BigQuery documentation with tbls integration guide**
=> sqlite and big query

.changeset/tasty-pears-walk.md, frontend/packages/cli/src/cli/initCommand/index.ts
I've added tbls, MySQL, SQLite, BigQuery setup to init command.
```bash
$ node frontend/packages/cli/dist-cli/bin/cli.js init
👾  Welcome to the @liam-hq/cli setup process! 👾
This `init` subcommand will guide you interactively through the setup.
🌟 This init command is a work in progress! 🌟
We're continuously improving it. Don't forget to run `npx @liam-hq/cli init` after updates for the latest features.
💡 Have feedback? Share it with us!
Visit https://github.com/liam-hq/liam/discussions to submit ideas or report issues.
🌟️ Love Liam ERD? Help us grow by starring our GitHub repository:
https://github.com/liam-hq/liam
----
Now, let's get started with setting up your Liam ERD project.
✔ Which Technology (database or ORM) are you using? SQLite (via tbls)
Note: Direct support is not available …
```
=> ✨update init instructions

docs/adr/20250116-use-dmmf-for-prisma-schema-parsing.md, docs/adr/template.md
Related PR:
- https://github.com/liam-hq/liam/pull/448
=> Add adr for prisma parser

.changeset/strong-deers-cry.md, frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/ErrorDisplay.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/NetworkErrorDisplay.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/ParseErrorDisplay.module.css
Refactored ErrorDisplay for responsive styling.
|🎨 Design|💻 ParseError|💻 NetworkError|
|--|--|--|
|<img width="250" alt="image" src="https://github.com/user-attachments/assets/16828d1e-b0a6-4991-b1be-5811fc7ac0a7" />|<img width="250" alt="image" src="https://github.com/user-attachments/assets/e6dbfaee-5109-4a79-ba2e-8fb36dd97df6" />|<img width="250" alt="image" src="https://github.com/user-attachments/assets/7c49da91-4ed8-4265-8366-f703e9eaaf7c" />|
🙅‍♂️ The position of error messages has not been as designed yet.
The position of error messages will be corrected in the next PR.
It may be necessary to change the structure of the component slightly.
=> 💄 Refactor ErrorDisplay for responsive styling

.changeset/hip-parents-heal.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/MobileToolbar.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/MobileToolbar.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/Toolbar.tsx, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/index.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/index.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- 💄 Enhance mobile Toolbar animation behavior and improve UI responsiveness
- and some refactors
* 738e66db : 💄 Enhance mobile Toolbar animation behavior and improve UI responsiveness **main change**
- Refactored `expand`, `collapse`, and `fadeInContent` animations for smoother transitions.
- Introduced `.initialOpen` class to differentiate initial and interactive states.
- Updated `MobileToolbar.tsx`:
- Added `useEffect` to reset `hasInteracted` on window resize, improving responsiveness.
- Adjusted class application logic to distinguish between initial and user-interacted states.
- Minor cleanup: removed redundant padding values in CSS.
* d0bd6bab : 💄 tweak width
- fixes wrong setting 🙏 
* ef47ff1f : 💄 fix font-family
- fixes wrong setting 🙏 
* 73f31eb7 : 💄 fix to use `align-items: …
=> 💄 Enhance mobile Toolbar animation behavior and improve UI responsiveness

frontend/apps/erd-web/app/layout.tsx
resolve: https://github.com/liam-hq/liam/issues/625
=> Fix font issue on safari

.changeset/famous-clouds-knock.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/usePopStateListener.ts, frontend/packages/erd-core/src/stores/userEditing/store.ts, frontend/packages/erd-core/src/utils/index.ts, frontend/packages/erd-core/src/utils/urlParams.ts
https://github.com/user-attachments/assets/5ad881ef-6728-4798-8925-64d5809ba12d
👀 It appears that unnecessary histories are stored when the RelatedTable is displayed at the first time.
Will continue to investigate.
=> ✨ Add support for hidden nodes in URL state management

frontend/apps/docs/content/docs/community-resources.mdx, frontend/apps/docs/content/docs/meta.json
I have created a page to summarize articles written by the community. Thanks to all of them 🥰
=> 📝 add community resources page

frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/MenuItemLink/MenuItemLink.tsx
follow-up https://github.com/liam-hq/liam/pull/628#discussion_r1937058010
=> tweak: Update ExternalLink condition in LeftPane

.cursorrules, CONTRIBUTING.md, frontend/apps/docs/content/docs/contributing/index.mdx, frontend/apps/docs/content/docs/contributing/repository-architecture.mdx, frontend/apps/docs/content/docs/meta.json
- **📝 Add repository architecture documentation**
- **📝 Add required file reads to cursorrules**
=> 📝 add document for repository architecture

.changeset/lazy-donkeys-worry.md, docs/packages-license.md, frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.module.css, frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.tsx, frontend/packages/ui/src/styles/variables.css
https://github.com/user-attachments/assets/8ef60a23-539e-42e4-8e2b-e3f68c55fb66
=> ✨ Add close functionality for mobile toolbar when clicking outside

.changeset/shiny-stingrays-approve.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css, frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx, frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/DesktopToolbar.module.css, frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.module.css
Refactor to change position of Toolbar along with Sidebar.
https://github.com/user-attachments/assets/9d722862-88db-4c1b-bbd6-97a9370f09fe
https://github.com/user-attachments/assets/1b2a185a-9c14-4dad-990f-a269fe698bf8
=> 🐛 Refactor ERD renderer toolbar positioning and visibility

.changeset/slimy-terms-joke.md, frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Comment/Comment.tsx
I adjusted the style of the TableDetail comment.
I changed the style from inline to block.
N/A
| ![スクリーンショット 2025-02-04 18 05 42](https://github.com/user-attachments/assets/5d776dce-7e8a-400f-967a-9dbed40752c2) | ![スクリーンショット 2025-02-04 18 04 39](https://github.com/user-attachments/assets/2e17ce15-59e9-45be-889b-7c60ca3c4951) | 
N/A
=> 💄 Refactor Comment component markup and styling

.github/workflows/_run_e2e_test.yml, .github/workflows/e2e-test.yml, .github/workflows/frontend-ci.yml, docs/packages-license.md, frontend/packages/e2e/.gitignore, frontend/packages/e2e/biome.jsonc, frontend/packages/e2e/package.json, frontend/packages/e2e/tests/page.test.ts, package.json, pnpm-lock.yaml, turbo.json
This PR is a rework based on PR #645.
I've introduced a new package folder (``e2e``) for end-to-end testing and enabled it to be run via ``pnpm test:turbo``. 
To automate the process, I've also added a GitHub Action.Please note that the CI results of these tests won't be visible until this branch is merged.
=> ✅ Add playwright test

.cursorrules
Added instructions to cursor to write @liam-hq/docs.
=> 📝 Add documentation guidelines to .cursorrules

frontend/apps/docs/.gitignore, frontend/apps/docs/app/global-error.tsx, frontend/apps/docs/instrumentation.ts, frontend/apps/docs/next.config.mjs, frontend/apps/docs/package.json, frontend/apps/docs/sentry.client.config.ts, frontend/apps/docs/sentry.edge.config.ts, frontend/apps/docs/sentry.server.config.ts, pnpm-lock.yaml
Add Sentry error monitoring to docs app.
I've added environment variables on vercel settings.
* for ERD Web
* https://github.com/liam-hq/liam/pull/411
Checked working properly on local environment.
=> 🔧 Add Sentry error monitoring to docs app

docs/adr/20250205-use-fuse-js.md
=> Add `Use fuse.js` ADR

.github/workflows/_run_e2e_test.yml, frontend/packages/e2e/playwright.config.ts, frontend/packages/e2e/tests/page.test.ts, frontend/packages/e2e/tsconfig.json
I forgot to add ``playwright.config.ts``, so I added it.🙏
Also, I forgot to add ``ts.config.json``, so I added it.🙏🙏
=> ✅ Add playwright config file

.github/workflows/trigger_dev.yml
tested:
- https://github.com/liam-hq/liam/actions/runs/13891945652
- failure pattern (slack notification sent)
- https://github.com/liam-hq/liam/actions/runs/13892004402
- success pattern
- resolve:
pr_agent:walkthrough
=> Auto deploy to trigger.dev

.github/workflows/trigger_dev_production.yml, .github/workflows/trigger_dev_staging.yml
tested: https://github.com/liam-hq/liam/pull/928/commits/8d7d6efc7443cca0ba93fc2e0573264efbcf18dc , https://github.com/liam-hq/liam/actions/runs/13920200751/job/38951427512
- resolve:
pr_agent:walkthrough
=> Trigger dev staging deploy

frontend/apps/app/libs/github/config.ts, frontend/packages/db/supabase/config.toml
- resolve:
pr_agent:walkthrough
=> staging PR

.changeset/chatty-kangaroos-return.md, docs/packages-license.md, frontend/packages/erd-core/package.json, frontend/packages/erd-core/src/features/reactflow/hooks/useCustomReactflow.ts, pnpm-lock.yaml
Due to e2e failure.  🙇  
temporary reverts liam-hq/liam#1045
=> Revert "⬆️ Update dependency @xyflow/react to v12.5.0"

docs/liam-migration-v1/product-required-document.md
Copies from the internal repository.
=> docs: add Product Required Document

frontend/packages/db/schema/schema.sql, frontend/packages/db/supabase/database.types.ts, frontend/packages/db/supabase/migrations/20250422034040_modify_github_repositories.sql, frontend/packages/jobs/src/tasks/review/savePullRequest.ts
=> Revert "Remove NOT NULL and UNIQUE constraints from github_repositories migration"

README.md
- document the star history on README
=> Add Star History section

frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeTimelineItems/useRealtimeTimelineItems.ts, frontend/apps/app/components/SessionDetailPage/schema.ts, frontend/apps/app/components/SessionDetailPage/services/convertTimelineItemToTimelineItemEntry.ts, frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/fetchDesignSessionWithTimelineItems.ts
- resolve: #2515
This PR addresses the CodeRabbit feedback from #2515 by implementing the following improvements:
- Add UUID validation to user_id and building_schema_version_id in timeline schema
- Refactor function declarations to use arrow functions for consistency
- Add proper error handling with console warnings for unknown timeline item types
- Fix missing dependency in useRealtimeTimelineItems hook
These changes improve type safety, code consistency, and error handling in the SessionDetailPage components.
=> ♻️ Refactor SessionDetailPage components based on CodeRabbit feedback

frontend/internal-packages/schema-bench/package.json, frontend/internal-packages/schema-bench/src/cli/evaluateSchema.ts, frontend/internal-packages/schema-bench/src/cli/executeOpenai.ts, frontend/internal-packages/schema-bench/src/cli/setupWorkspace.ts, frontend/internal-packages/schema-bench/src/cli/utils/error.ts, frontend/internal-packages/schema-bench/src/cli/utils/index.ts, frontend/internal-packages/schema-bench/src/cli/utils/workspace.ts, frontend/internal-packages/schema-bench/src/executors/openai/index.ts, frontend/internal-packages/schema-bench/src/executors/openai/openaiExecutor.test.ts, frontend/internal-packages/schema-bench/src/executors/openai/openaiExecutor.ts, frontend/internal-packages/schema-bench/src/executors/openai/schemaJsonSchema.ts, frontend/internal-packages/schema-bench/src/executors/openai/types.ts, frontend/internal-packages/schema-bench/src/index.ts, pnpm-lock.yaml
This change implements an OpenAI executor for the schema-bench package to enable automated database schema generation from natural language specifications. This functionality is essential for benchmarking and testing schema generation capabilities using OpenAI's Structured Output API.
Now you can use ` pnpm --filter @liam-hq/schema-bench executeOpenai`  🤖 
- **Add OpenAI integration**: Implemented OpenAI executor using SDK v5.9.2 with o4-mini model for schema generation
- **Structured output support**: Added JSON Schema validation to ensure consistent output format compatible with @liam-hq/db-structure
- **CLI batch execution**: Created command-line interface for processing multiple inputs and saving outputs to benchmark workspace
- **Comprehensive schema support**: Implemented support …
=> feat: add OpenAI executor to schema-bench

frontend/internal-packages/agent/src/chat/workflow/README.md, frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts, frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts, frontend/internal-packages/agent/src/chat/workflow/types.ts, frontend/internal-packages/agent/src/deepModeling.test.ts, frontend/internal-packages/agent/src/deepModeling.ts
- resolve: https://github.com/route06/liam-internal/issues/5062
Currently, the `generatedAnswer` generated in `designSchemaNode` is stored in state and later saved as timeline_items in `finalizeArtifactsNode`. However, by saving directly to timeline_items at the `designSchemaNode` stage, we can eliminate the need to store `generatedAnswer` in state, enabling the following optimizations:
- **Reduced State Size**: No need to carry `generatedAnswer` through the workflow state
- **Improved Data Flow**: Immediate storage at generation time, clearer flow
- **Performance Improvement**: Reduced overhead from carrying unnecessary data
- **Code Simplification**: Elimination of duplicate save logic
Additionally, to enable meaningful testing, we changed the `deepModeling` function's return value to …
=> 🔧(agent): Simplify deepModeling return type to WorkflowState

frontend/apps/app/components/MarkdownContent/MarkdownContent.module.css, frontend/apps/app/components/MarkdownContent/MarkdownContent.tsx, frontend/apps/app/components/SessionDetailPage/components/Chat/AnimatedChatDemo.tsx, frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.stories.tsx, frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.module.css, frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.module.css, frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.stories.tsx, frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/UserMessage/UserMessage.module.css, frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.tsx, frontend/apps/app/components/SessionDetailPage/factories.ts, frontend/apps/app/package.json, frontend/internal-packages/db/src/factories/buildingSchemaVersions.ts, pnpm-lock.yaml
- resolve:
The current log messages and markdown content in SessionDetailPage lack proper typography and spacing, making them difficult to read.
This change improves readability and visual hierarchy for better user experience.
Before: 
https://liam-storybook-j9eq114z8-liambx.vercel.app/?path=/docs/app-components-sessiondetailpage-components-chat-components-timelineitem-components-logmessage--docs
After: https://liam-storybook-git-feature-log-message-styling-liambx.vercel.app/?path=/docs/app-components-sessiondetailpage-components-chat-components-timelineitem-components-logmessage--docs
https://github.com/user-attachments/assets/f2cfb6d9-c749-4432-85c9-36d5533ce30f
Before: https://liam-storybook-j9eq114z8-liambx.vercel.app/?path=/docs/app-components-sessiondetailpage-components-chat--docs …
=> 💄 Improve log message and markdown content styling

frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/executeDdlNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/generateUsecaseNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.ts, frontend/internal-packages/agent/src/chat/workflow/nodes/webSearchNode.ts
- resolve: Timeline logging improvements for better user experience
The current timeline logging messages were too technical and verbose, creating a poor user experience. Users need clearer, more descriptive feedback about what's happening during the database design workflow.
=> 🔧(agent): optimize timeline logging for better user experience

frontend/internal-packages/agent/package.json, frontend/internal-packages/agent/scripts/executeDesignProcess.ts, frontend/internal-packages/agent/tsconfig.json, pnpm-lock.yaml
- resolve: N/A (Developer experience improvement)
Added a dedicated script to execute only the design process for easier CLI debugging. This allows developers to efficiently test and debug the design process functionality in a local environment without running the full workflow.
1. **Design Process Dedicated Script**: Added executeDesignProcess.ts script to run only the design process independently
2. **Enhanced Logging System**: Added configurable log levels (DEBUG, INFO, WARN, ERROR) for better debugging experience
3. **Improved TypeScript Type Safety**: Removed type assertions and implemented proper type guards
4. **Code Quality Improvements**: Reduced complexity warnings through function decomposition and eliminated code duplication
These changes enable developers to efficiently test …
=> ✨ Add dedicated design process script for CLI debugging

frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/components/SendButton/SendButton.module.css, frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/components/SendButton/SendButton.tsx, frontend/packages/ui/src/components/IconButton/IconButton.module.css, frontend/packages/ui/src/components/IconButton/IconButton.stories.tsx, frontend/packages/ui/src/components/IconButton/IconButton.tsx
- resolve: N/A
The previous SendButton implementation had several issues:
1. **Shape inconsistency**: The button could become rectangular in certain conditions due to lack of fixed dimensions
2. **Code duplication**: Custom tooltip implementation when IconButton already provides this functionality
3. **Maintainability**: Multiple style states managed manually instead of leveraging existing UI components
This refactoring simplifies the SendButton component by leveraging the existing IconButton component from the UI library. This ensures consistent circular button shape and reduces code duplication.
- Replaced custom Button implementation with IconButton component (which has fixed 1.5rem × 1.5rem dimensions)
- Simplified CSS by removing redundant styles and states
- Enhanced IconButton to …
=> ♻️ Refactor SendButton to use IconButton component

frontend/apps/erd-web/.next/trace
=> tweak: $ rm -rf frontend/apps/erd-web/

frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/AiMessage.module.css, frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/ToolCalls/ToolCalls.tsx, frontend/apps/app/components/SessionDetailPage/components/Chat/factories.ts, frontend/apps/app/components/SessionDetailPage/hooks/useStream/parseSse.ts, frontend/apps/app/eslint-suppressions.json, frontend/internal-packages/agent/src/db-agent/invokeDesignAgent.ts, frontend/internal-packages/agent/src/pm-agent/invokePmAnalysisAgent.ts, frontend/packages/ui/src/icons/index.ts
- Related to: #3030
This PR addresses the code review feedback provided by CodeRabbit on PR #3030. The changes focus on improving code quality, type safety, and consistency across the codebase.
1. **Icon import consistency**: Migrated Wrench icon import from lucide-react to @liam-hq/ui package for consistency
2. **Test factory improvements**: Added tool_calls data structure to AI message factory for better testing capabilities
3. **CSS variable usage**: Replaced hardcoded padding values with CSS variables for better maintainability
4. **Type safety improvements**: Refactored message factories to use proper class constructors instead of type assertions
5. **Null safety enhancements**: Improved null safety in agent reasoning parsing with optional chaining
These changes improve code …
=> ♻️ Address CodeRabbit review feedback from streaming PR
