liam-hq/liam

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
- frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
|before|after|
| --- | --- |
| <img width="1397" alt="スクリーンショット_2024-12-05_17_04_49" src="https://github.com/user-attachments/assets/c58bf772-8d00-4664-92c2-2987679cd548"> | <img width="1397" alt="スクリーンショット_2024-12-05_17_03_56" src="https://github.com/user-attachments/assets/8ee4484c-976f-486e-8f7b-24fe4685d9a0"> |
> fix: fix layout for text overflow

- frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/mergeDBStructures.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.ts
In the PostgreSQL parser, the SQL string is now split into chunks of 1000 lines each time it is processed.
Several errors were occurring when entering huge SQL strings.
https://github.com/liam-hq/liam/pull/155/commits/1a4246e5e48c14ba4262e95b83330a5628ae34bf
https://github.com/liam-hq/liam/actions/runs/12157819490/job/33904440226#step:4:39
https://github.com/liam-hq/liam/pull/155/commits/9a37df9ed49fa1f7209882eaf0fe5ad1588be369
https://github.com/liam-hq/liam/actions/runs/12158068823/job/33905205933#step:4:39
```
TypeError: Ma[F[(F[((c + 12) >> 2)] >> 2)]] is not a function
❯ tb ../../node_modules/.pnpm/pg-query-emscripten@5.1.0/node_modules/pg-query-emscripten/pg_query.js:18:10370
❯ ef ../../node_modules/.pnpm/pg-query-emscripten@5.1.0/node_modules/pg-query-emscripten/pg_query.js:16:59697 …
```
> fix(postgres-parser): Implement chunked SQL processing and merge DB structures

- frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
- frontend/packages/db-structure/src/schema/dbStructure.ts
- frontend/packages/db-structure/src/schema/factories.ts
- frontend/packages/db-structure/src/schema/index.ts
Add foreign key parsing for schemarb parser.
For postgres paser:
* https://github.com/liam-hq/liam/pull/131
Two patterns of notation for foreign key constraints in schema.rb
1️⃣: Foreign key constraints at the same time as table creation
```rb
create_table :products do |t|
t.references :category, foreign_key: true
end
```
2️⃣: Foreign key constraints after table creation
```rb
add_foreign_key :articles, :authors
```
I looked through several Rails projects and they are all written in  2️⃣.
https://github.com/mastodon/mastodon/blob/main/db/schema.rb
https://github.com/autolab/Autolab/blob/master/db/schema.rb
https://github.com/lobsters/lobsters/blob/master/db/schema.rb
https://github.com/astuto/astuto/blob/main/db/schema.rb
https://github.com/chatwoot/chatwoot/blob/develop/db/schema.rb
It …
> Add foreign key parsing for schemarb parser

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
I fixed it so that the table name of the selected TableNode is displayed, as previously all TableNodes showed only 'Table Name' regardless of which one was selected.
> fix: display selected table name

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx
I fixed an oversight in ShowModeMenu by adding the display of label text. 🙏 
|<img width="1113" alt="スクリーンショット 2024-12-06 15 10 55" src="https://github.com/user-attachments/assets/759b6893-d919-4a1e-bfee-e31c150ee369"> |<img width="1114" alt="スクリーンショット 2024-12-06 15 09 04" src="https://github.com/user-attachments/assets/c4008888-b29f-4d1d-af24-cc70b61dd9e9"> |
> feat: Add label in ShowModeMenu

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
I adjusted the animation-duration for showing and hiding the TableDetail to 165ms.
> feat: Adjust animation-duration for TableDetail toggle to 165ms

- frontend/packages/db-structure/src/parser/__tests__/testcase.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
The commonisation of test cases implemented at https://github.com/liam-hq/liam/pull/169 is reflected in some of the tests
This is still a work in progress and has not been reflected in all test cases.
- **test: Add test case for 'not null' column in parser tests**
- **test: Add test cases for nullable columns in parser tests**
- **test: Add test cases for default value as string columns in parser tests**
- **test: Add test cases for default value as integer columns in parser tests**
- **test: Add test cases for default value as boolean columns in parser tests**
- **test: Add test cases for unique constraints columns in parser tests**
> maintenance: enhance parser test cases 2

- frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
Support foreign key parsing for postgres parser.
Supported format in this pr.
```sql
CREATE TABLE posts (
id SERIAL PRIMARY KEY,
user_id INT NOT NULL
);
ALTER TABLE posts
ADD CONSTRAINT fk_posts_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL;
```
* https://github.com/liam-hq/liam/pull/131
* https://github.com/liam-hq/liam/pull/167
> Add foreign key parsing for postgres parser

- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
- frontend/packages/db-structure/src/parser/utils/handleOneToOneRelationships.ts
- frontend/packages/db-structure/src/parser/utils/index.ts
Support `ONE_TO_ONE` cardinality for schema.rb parser.
If foreign key is unique, it must be one to one relationship.
```ruby
create_table "posts" do |t|
t.bigint "user_id", unique: true
end
add_foreign_key "posts", "users", column: "user_id", name: "fk_posts_user_id"
```
* https://github.com/liam-hq/liam/pull/166
> feat: parse one to one relationships for schema.rb

- frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
- frontend/packages/db-structure/src/parser/schemarb/convertColumnType.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- Updated snapshots and test cases to reflect the converted column types, e.g., `string` -> `varchar`, `datetime` -> `timestamp`.
- Added `convertColumnType` function to map Rails schema.rb types to PostgreSQL column types, aligning with ActiveRecord::ConnectionAdapters implementation.
> Map ActiveRecord column types to PostgreSQL equivalents

- .github/workflows/license-frontend.yml
- frontend/docs/packages-license.md
I have chosen a generic name so that it can be used with other CI triggers, but I would like to change it to a specific name because I feel that it mixes up the usage and induces over-authorization.
I have already created `vars.LICENSE_CI_TRIGGER_APP_ID` and `secrets.LICENSE_CI_TRIGGER_APP_PRIVATE_KEY`.
* https://github.com/liam-hq/liam/settings/variables/actions
* https://github.com/liam-hq/liam/settings/secrets/actions
Nothing
✅ https://github.com/liam-hq/liam/actions/runs/12231131566
After this PR is merged, I will remove the variable and secret.
* `vars.CI_TRIGGER_APP_ID`
* `secrets.CI_TRIGGER_APP_PRIVATE_KEY`
> Rename Actions secret and variable

- frontend/packages/db-structure/src/parser/__tests__/testcase.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
The commonisation of test cases implemented at https://github.com/liam-hq/liam/pull/169, https://github.com/liam-hq/liam/pull/181 are reflected in some of the tests
This is still a work in progress and has not been reflected in all test cases.
- **test: Add test case for 'column comment' in parser tests**
- **test: Add test case for 'index (unique: false)' in parser tests**
- **test: Add test case for 'index (unique: true)' in parser tests**
- **test: Remove unused userTable setup in PostgreSQL index tests**
> maintenance: enhance parser test cases 3

- frontend/config/dependency_decisions.yml
- frontend/docs/packages-license.md
💡 This is a pull request to the https://github.com/liam-hq/liam/pull/179.
By introducing Eclipse 2.0 licensed packages with Apache-2.0 licensed OSS, It seems not to be any license conflicts.
* https://opensource.org/license/apache-2-0
* https://opensource.org/license/epl-2-0
When developing an open-source project under the Apache-2.0 license and considering the use of a package under the Eclipse Public License 2.0 (EPL-2.0), potential license conflicts need to be carefully evaluated. Here’s an analysis based on the license definitions:
1. Redistribution Conditions of EPL-2.0
If you are incorporating a package under the EPL-2.0 license, the entire software does not need to adopt the EPL-2.0 license. However, if you modify and redistribute code governed by EPL-2.0, those modifications must …
> Permit Eclipse 2.0 License

- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
Support `FalseNode` for `create_table` `id` args.
`id: true` is not supported in Rails 8.0.0, so there's no need to support it.
schema.rb:
```ruby
create_table "users", id: true do |t|
t.string "name"
end
```
Error occur:
```ruby
[ERROR] undefined method `to_sym' for true
```
Reason:
```ruby
def column(name, type, index: nil, **options)
name = name.to_s
type = type.to_sym if type # <-- This is the cause
end
```
https://github.com/rails/rails/blob/v8.0.0/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L490
> Support FalseNode for id args

- frontend/docs/packages-license.md
- frontend/packages/cli/src/cli/runPreprocess.ts
- frontend/packages/db-structure/package.json
- frontend/packages/db-structure/src/parser/errors.ts
- frontend/packages/db-structure/src/parser/index.test.ts
- frontend/packages/db-structure/src/parser/index.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/index.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
- frontend/packages/db-structure/src/parser/types.ts
- frontend/pnpm-lock.yaml
Even if there are unsupported syntaxes, only warnings are displayed and the system exits normally.
Previously, if a name was passed to `create_table` as a variable, an error would occur because it was not a string.
```rb
variable = "posts"
create_table variable do |t|
end
```
This does not happen very often because schema.rb is generally generated code, but it often happens when users write their own table definitions while using ActiveRecord's DSL, such as [Ridgepole](https://github.com/ridgepole/ridgepole).
Error information is logged but exits normally.
The output is still dirty, but the formatting of the logs will be tackled in a separate issue.
```
node packages/cli/dist-cli/bin/cli.js erd build --input ../../../test/db/Schemafile --format schemarb
UnsupportedTokenError: Expected a …
```
> feat: show warning errors when table name is not string

- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- frontend/packages/db-structure/src/parser/schemarb/singularize.test.ts
- frontend/packages/db-structure/src/parser/schemarb/singularize.ts
`add_column_key()` to retrieve relationships even if the column name is omitted.
I have ported the method of `ActiveSupport::Inflector#singularize`.
> fix: Add support for foreign key without column name

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx
Added RelationshipEdge styling:
* When hovering over a node, only the primary-to-external edges are colored and animated.
* When hovering over a edge, edges are also colored and animated.
https://github.com/user-attachments/assets/b5634ddc-a787-4bae-8f1c-221a8cd202b7
> Add edge styling (animation and coloring)

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/index.ts
- frontend/packages/erd-core/src/stores/index.ts
- frontend/packages/erd-core/src/stores/userEditing/actions.ts
- frontend/packages/erd-core/src/stores/userEditing/hooks.ts
- frontend/packages/erd-core/src/stores/userEditing/index.ts
- frontend/packages/erd-core/src/stores/userEditing/store.ts
- frontend/packages/erd-core/src/types/css.d.ts
- frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
Keep the active table in the global state, so that the TableDetail can also be opened from the left pane.
https://github.com/user-attachments/assets/dd0052aa-04bd-46b0-bd3d-e6a5ab1188b0
> feat: store active table name

- frontend/packages/cli/src/cli/getInputContent.test.ts
- frontend/packages/cli/src/cli/getInputContent.ts
- frontend/packages/cli/src/cli/runPreprocess.test.ts
- frontend/packages/cli/src/cli/runPreprocess.ts
Support input url option for cli.
```sh
./dist-cli/bin/cli.js erd build --input https://github.com/someapp/someapp/blob/main/db/schema.rb  --format schemarb
```
In most cases, we will receive a GitHub URL.
In that case, convert it to a RawContent URL such as:
```
https://raw.githubusercontent.com/someapp/someapp/main/db/schema.rb
```
> Support input url option for cli

- .github/workflows/license-frontend.yml
- frontend/docs/packages-license.md
Stop git commit only timestamp update in license report.
e.g. https://github.com/liam-hq/liam/commit/0a5510d877c1e6575f2675aeb9cfc8a8e9fa444d
N/A
Removed the timestamp line from license report in GitHub Actions workflow.
✅ This job removed the timestamp line.
https://github.com/liam-hq/liam/actions/runs/12269897007/job/34234220798
> Stop git commit only timestamp update in license report

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx
I switched to this one because it was potentially more visible.
> feat: Replace smooth step path with bezier path in RelationshipEdge component

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Comment/Comment.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
- frontend/packages/ui/src/components/Drawer/Drawer.tsx
> feat: replace Comment div with DrawerDescription component and add aria-describedby for accessibility

- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
Simplified state management in TableDetailDrawer.
This ensures that the TableNode is displayed even if it is clicked on in succession.
https://github.com/user-attachments/assets/68926485-9755-4fdc-b9f2-e66173f9f7a8
However, this has made it impossible to display the closing animation.
As it is difficult to reconcile the two, priority was given to opening them in succession this time.
> fix: simplify TableDetailDrawer state management

- frontend/packages/db-structure/src/parser/__tests__/testcase.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
The commonisation of test cases implemented at https://github.com/liam-hq/liam/pull/169, https://github.com/liam-hq/liam/pull/181, https://github.com/liam-hq/liam/pull/185 are reflected in some of the tests.
Looks like it's a done deal once and for all.
- test: Add foreign key test cases for one-to-many, one-to-one, and actions
> maintenance: enhance parser test cases 4

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/getElkLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
- frontend/packages/erd-core/src/schemas/showMode/index.ts
- frontend/packages/erd-core/src/schemas/showMode/schemas.ts
- frontend/packages/erd-core/src/schemas/showMode/types.ts
- frontend/packages/erd-core/src/stores/userEditing/actions.ts
- frontend/packages/erd-core/src/stores/userEditing/store.ts
I have adopted the ELK Layered algorithm for automatic layout.
Additionally, I have implemented a "Table Name" mode.
https://github.com/user-attachments/assets/24f7f990-a0ab-41a1-9484-97b93d21e629
- [feat: use org.eclipse.elk.layered in elk.algorithm](https://github.com/liam-hq/liam/pull/214/commits/c725c098298eac3c351878fd2dac62eb4edc65a9)
- Adopted ELK Layered algorithm for automatic layout
- [feat: implement show mode management with user editing store](https://github.com/liam-hq/liam/pull/214/commits/8ac6a9bd7e36676e6b356a01347dba6cabbe1b2f)
- Changed the showMode variable, which was previously managed within the ShowModeMenu component, to be managed by the userEditingStore
- [feat: enhance convertDBStructureToNodes to support show …
> feat: use org.eclipse.elk.layered in elk.algorithm

- frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
I ensured that Nodes are always placed on top of Edges.
|<img width="1484" alt="スクリーンショット 2024-12-12 14 25 55" src="https://github.com/user-attachments/assets/6fc2cb66-0a36-47de-b6b8-45086d7346d2" /> |<img width="1493" alt="スクリーンショット 2024-12-12 14 25 20" src="https://github.com/user-attachments/assets/28a093e4-1a0c-4397-9fe3-213b20fefb79" /> |
> feat: add zIndex property to node style in convertDBStructureToNodes

- frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.ts
Updated `processSQLInChunks` to ignore lines starting with `--` during processing by filtering them out.
N/A
- tested manually ✔️
> Fix handling of `--` comment lines with semicolons in `processSQLInChunks`

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
Enable Figma-like Viewport Controls:
* pan: Space + scroll, middle or right mouse
* zoom: pitch or cmd + scroll
* create selection: drag mouse
ref: https://reactflow.dev/learn/concepts/the-viewport#figma-like-viewport-controls
> feat: Enable panning on scroll

- frontend/.changeset/new-deers-smash.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
Add tooltip functionality to TableHeader component
> feat(ERDRenderer): Add tooltip functionality to TableHeader component

- frontend/packages/cli/src/cli/runPreprocess.ts
- frontend/packages/db-structure/src/parser/index.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
Stop throwing errors and return the error class to the caller.
This makes it easier to take error handling into account on the CLI side. For example, adjusting the log level.
> refactor: reduce throwing errors

- frontend/apps/docs/content/docs/debug.mdx
To adjust the design, a page is provided where all components can be viewed once.
This will be removed before release.
ref: https://liam-docs-k3x9juyjw-route-06-core.vercel.app/docs/debug
> debug(docs): Add page with various components and examples

- .changeset/nasty-toes-fix.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
A cardinality comment has been added.
Currently, cardinality is displayed on hover, but the implementation for displaying it on click will be handled in a separate PR.
preview: https://liam-erd-sample-plyauxlxb-route-06-core.vercel.app/
> Add cardinality comments to TableNode component

- .changeset/dull-frogs-admire.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
Fixed border radius for TABLE_NAME show mode.
Before
After
> Fixed border radius for TABLE_NAME show mode.

- frontend/apps/docs/source.config.ts
|before|after|
| --- | --- |
| <img width="849" alt="スクリーンショット 2024-12-13 17 06 41" src="https://github.com/user-attachments/assets/9d139b1e-1038-477f-b26d-3b0fe9ab0118" /> | <img width="849" alt="スクリーンショット 2024-12-13 17 07 22" src="https://github.com/user-attachments/assets/86a32cf9-a936-4d0b-a6e1-6d254f2f52db" /> |
ref: https://liam-docs-a0f2ekb62-route-06-core.vercel.app/docs/static-build/getting-started
ref: https://github.com/fuma-nama/fumadocs/discussions/946#discussioncomment-10921878
As the document is not to be published, no changeset has been added.
> feat: Add rehypeCodeOptions for theme customization in MDX configuration

- .changeset/tiny-needles-refuse.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
When there is only one target for updating, it is simpler to use the updateEdge function instead of the setEdges function, so I replaced it with the updateEdge function.
ref. https://github.com/xyflow/xyflow/discussions/4496#discussioncomment-10189904
> refactor: optimize edge highlighting using useReactFlow hooks

- .changeset/tender-cooks-melt.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
I was reading the react flow documentation and noticed that the Node disappeared when I pressed the delete key during selection 😂
https://github.com/user-attachments/assets/b56c3fd3-809e-44ed-b696-5440b79df7e1
ref: https://reactflow.dev/api-reference/react-flow#keyboard-props
That functionality is not needed and has been turned off.
> fix: disable delete key functionality in ERDContent component

- .changeset/ten-ravens-wave.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/getElkLayout.ts
I adjusted the layout so that the nodes are arranged from left to right.
> feat: update ELK layout options for improved node placement and spacing

- .changeset/config.json
Follow-up to https://github.com/liam-hq/liam/pull/243
From https://github.com/liam-hq/liam/pull/243, the `Version Package` PR was no longer being created. 🙇 
It seems that the changelog package could not be found, possibly due to the use of a symlink. 
Referring to https://github.com/changesets/changesets/issues/945#issuecomment-1264614341, I attempted to fix it by updating relative path.
N/A
- Updated the `changelog` path in `.changeset/config.json` 
- Made a test commit: 011ace0a8e9a71fbb2cc663557d9583112fa1ee5 
- Verified that GitHub Actions ran successfully: 👌 https://github.com/liam-hq/liam/actions/runs/12314225561.
- Confirmed that the `Version Package` PR was successfully created: 👌 https://github.com/liam-hq/liam/pull/254.
Additionally, confirmed that the `pnpm changeset` command …
> Review changeset configuration to resolve errors in GitHub Actions

- frontend/.changeset/hot-pillows-give.md
- frontend/.changeset/shaggy-plants-tan.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/index.ts
- frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
- frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
- frontend/packages/ui/src/icons/Eye.tsx
- frontend/packages/ui/src/icons/EyeClosed.tsx
- frontend/packages/ui/src/icons/index.ts
https://github.com/user-attachments/assets/e9cb717d-dd4f-4e84-a7f1-6fbbfdd0be25
Currently, a fitView is executed when a Table node is returned from hidden to visible. This will be fixed in another PR.
> feat: Enabled toggling the visibility of Table Nodes from the Left Pane

- frontend/.changeset/late-clouds-raise.md
- frontend/packages/cli/src/cli/index.test.ts
- frontend/packages/cli/src/cli/index.ts
Refactored the CLI initialization to dynamically fetch the version number from `package.json` using `createRequire` from Node.js. This ensures the CLI version is automatically synchronized with the package version.
> Use version from `package.json` in Liam CLI

- frontend/.changeset/two-rockets-shave.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
Fixed excessive highlighting of cardinality elements.
Before
After
> Fixed excessive highlighting of cardinality elements.

- frontend/.changeset/heavy-dingos-dream.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
https://github.com/user-attachments/assets/aa810c10-039b-4216-a6a4-52f496e86297
> feat: implement `tidy up` button

- frontend/.changeset/violet-chicken-mate.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
The highlighting of single edges is removed as a feature as it does not contribute to the readability of the ER diagram.
This is motivated by the need to reduce the re-rendering that occurs when moving on the canvas.
https://github.com/user-attachments/assets/e0f08278-3859-43ef-93f1-cda8ced3692c
https://github.com/user-attachments/assets/388e61c4-dcb0-4da0-b93d-dd6e062a1560
```sh
npx react-scan@latest https://liam-erd-sample-gz7pse1m5-route-06-core.vercel.app/
```
> fix: Remove the highlight on Edge hover to prevent performance degradation

- frontend/.changeset/neat-squids-brush.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
Although it does not contribute to performance, useEffect has been removed because less useEffect is desirable.
> refactor: reduce useEffect usage in ERDContent component

- frontend/.changeset/small-cameras-scream.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- https://github.com/liam-hq/liam/pull/274
The above change caused a problem with the display when switching show mode.
This was because re-rendering was also required when changing the show mode.
https://github.com/user-attachments/assets/e3656514-0b31-42ca-8365-9cb5af911a94
> fix: Fixed an issue where edges were displayed incorrectly when switching the show mode

- frontend/.changeset/twelve-impalas-type.md
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
- frontend/packages/erd-core/src/stores/userEditing/hooks.ts
The feature to open TableDetail when opened with a URL with a query parameter did not work in some cases, which will be corrected.
https://liam-erd-sample-pzarkcxaz-route-06-core.vercel.app/?active=featured_tags
> fix: Fixed an issue where URL sharing in TableDetail sometimes did not work correctly

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.tsx
Optimize TableColumn component by caching relationship checks.
Introduced useMemo to cache `isSource` and `targetCardinality` computations.
Triggered `handleMouseLeaveNode` manually on the accounts table node to measure performance impact.
<details><summary>Demo</summary>
https://github.com/user-attachments/assets/9cde8ec3-49ca-455a-afe5-a03f751fba1d
</details>
before: ~660 ms
after: ~170 ms
|  | before 90fae17723f7 | after f843a99746a2c37  |
|--------|--------|--------|
|  | <img width="1216" alt="main1-sk" src="https://github.com/user-attachments/assets/870f0f61-6ae8-46a4-b5c6-9565682551b7" />  | <img width="1207" alt="hoshino1-sk" src="https://github.com/user-attachments/assets/f5c0e444-e7b9-46fd-94bc-d5f636d58a53" /> |
before: ~0.6 ms
after: ~0.1 ms
|  | before 90fae17723f7 | after …
> Optimize TableColumn component by caching relationship checks

- frontend/.changeset/thirty-rabbits-travel.md
- frontend/packages/db-structure/src/index.ts
- frontend/packages/db-structure/src/schema/dbStructure.ts
- frontend/packages/db-structure/src/schema/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/Cardinality/Cardinality.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumnList.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts
- frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
- Continued from https://github.com/liam-hq/liam/pull/278
The source and handle are now calculated only once at the beginning.
In addition to TableColumn, calculated values are now used in TableHeader.
Triggered `handleMouseLeaveNode` manually on the accounts table node to measure performance impact. (It is same as #278 )
I then checked the Ranked tab in the React Dev tool.
TableHeader calculations are at the top of the list.
TableHeader calculations have disappeared from the top!
> refactor: Reduced performance degradation caused by calculations for source and target

- frontend/.changeset/sharp-queens-repair.md
- frontend/packages/erd-core/src/stores/userEditing/store.ts
The default mode has been changed to reduce performance issues and affect the user's first-time experience.
> ✨: Changed the default show mode to 'Table name only'

- frontend/.changeset/many-wasps-join.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.module.css
Reduce the width of TableDetail to prevent TableNode from being obscured . 
width: 500 -> 300.
> Reduce the width of TableDetail to prevent TableNode from being obscured

- frontend/.changeset/sour-candles-pay.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts
Highlight related edges and cardinalities when a TableNode is active.
Preview: https://liam-erd-sample-gx3t0p2yn-route-06-core.vercel.app/
> Highlight related edges and cardinalities when a TableNode is active.

- frontend/.changeset/unlucky-cycles-reflect.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- **refactor: Unified showmode invocation**
- **refactor: Extract edge highlighting logic into reusable functions**
> refactor: Minor refactoring of ERDContent

- frontend/.changeset/stale-bags-join.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
Enable clicking AppBar (mainly `Copy Link`) while Table Detail opened.
https://github.com/user-attachments/assets/2cb0a089-1645-4f43-b42c-9d8468168716
There is an Issue that option `modal={false} leaves Drawer open with `pointer-events: none`.
This PR includes the workaround.
* https://github.com/emilkowalski/vaul/issues/492
> Enable clicking while Table Detail opened

- frontend/.changeset/twenty-eggs-beam.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
Resolved the problem that prevented the **column type** from being shown on TableNode hover.
In contrast to the design, where column types are shown for all relevant TableNodes on hover, this implementation displays the column type only for the hovered TableNode.（In order to fix the bug quickly.）
> Restored columnType visibility

- frontend/.changeset/empty-numbers-exist.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Spinner/Spinner.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Spinner/Spinner.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Spinner/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
https://github.com/user-attachments/assets/e8ab2d1b-f78e-4921-a0e9-58842dd47ee2
> feat: add loading spinner animation

- frontend/apps/erd-sample/scripts/update_dist_content.mjs
I implemented Google Tag Manager to enable quantitative data collection on how this application was used during internal reviews.
> 📈 Add Google Tag Manager scripts to update_dist_content.mjs

- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
- frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
- Resolve Issue Where Table Display Toggle Icon Overlaps with Scrollbar in Left Pane
https://github.com/user-attachments/assets/02d78bc9-efe2-4a7e-8aaa-e9a8a34166c7
- Adjusted the position, spacing, and alignment of the eye icon for toggling table display in the left pane so that it no longer overlaps with the scrollbar.
- Adjusted the viewBox size of the TableName icon's SVG.
> 💄 feat: update styling sidebar menu

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
Added shadow to Table Node to add a floating nuance to give the impression that it is not too attached to an unrelated Edge.
https://github.com/user-attachments/assets/78e1f4ef-dfa7-4269-90fe-3341f2c87d65
- Add nuance shadow for TableNode.
> 💄 feat: add nuance shadow for TableNode

- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
For now, it appears that setting `modal={false}` in https://github.com/liam-hq/liam/pull/292 suppresses the re-rendering of the `RelatedTables` component. Therefore, I explicitly specified the `key` property.
https://github.com/liam-hq/liam/pull/316/commits/690b1594bb2e7a45150dca7eb4a1747c9b9975c2
https://github.com/user-attachments/assets/888f476b-9db8-490f-af65-d3d4bf4ed7e5
> Ensure `related tables` reload when any table node becomes active

- frontend/.changeset/mighty-shoes-confess.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts
- continued: https://github.com/liam-hq/liam/pull/309
Support for edges with `highlightNodesAndEdges()`!
> refactor: Refactoring of highlight edges on active table

- frontend/.changeset/happy-toes-speak.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useSyncHighlightsActiveTableChange.ts
Fixed an issue where opening an active table from a query parameter would not highlight it 👍🏻 
~Merge after the following PR merged.~
- https://github.com/liam-hq/liam/pull/312
- Click on table node → Target node becomes active
- Click on table name in LeftPane → target node becomes active
- URL contains `?active=${tableName}` → target node becomes active
> fix: Fixed an issue where opening an active table from a query parameter would not highlight it

- frontend/.changeset/big-impalas-call.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useSyncHighlightsActiveTableChange.ts
- ref: https://github.com/liam-hq/liam/pull/313
- ref: https://github.com/liam-hq/liam/pull/312
- ref: https://github.com/liam-hq/liam/pull/309
Highlighting on hover is now also supported with `highlightNodesAndEdges()`.
~Merge after the following PR merged.~
- https://github.com/liam-hq/liam/pull/313
- Click on table node → Target node becomes active
- Click on table name in LeftPane → target node becomes active
- URL contains ?active=${tableName} → target node becomes active
- Hover on table node → Target node becomes hovered state
> refactor: integrate highlightNodesAndEdges function for improved node and edge highlighting on hover

- frontend/.changeset/chatty-poems-talk.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
- frontend/packages/erd-core/src/features/gtm/utils/index.ts
- frontend/packages/erd-core/src/features/gtm/utils/selectTableLogEvent.ts
add types for select table logging 
<details><summary>main area</summary>
</details>
> 📈 add types for select table logging

- frontend/.changeset/calm-lobsters-jam.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/type.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts
Remove `highlightedHandles` that were used to highlight cardinality.
related to:
* https://github.com/liam-hq/liam/pull/319
> refactor: Remove highlightedHandles

- frontend/.changeset/empty-parents-knock.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useSyncHiddenNodesChange.ts
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx
- frontend/packages/erd-core/src/schemas/queryParam/schemas.ts
- frontend/packages/erd-core/src/stores/userEditing/actions.ts
- frontend/packages/erd-core/src/stores/userEditing/store.ts
hidden nodes can now be reflected from query parameters!
https://github.com/user-attachments/assets/c287e2a5-be9c-47f0-906a-6b0ed39a540a
As a side effect, the hidden information can now be maintained even if the showMode is changed 👍🏻 
However, the URL looks a little bad, as following:
https://liam-erd-sample-a6smzxm8k-route-06-core.vercel.app/?hidden=account_aliases%2Caccount_conversations%2Caccount_deletion_requests%2Caccount_domain_blocks%2Caccount_migrations%2Caccount_moderation_notes%2Caccount_notes%2Caccount_pins%2Caccount_relationship_severance_events%2Caccount_stats%2Caccount_statuses_cleanup_policies%2Caccount_warning_presets%2Caccount_warnings%2Caccounts%2Caccounts_tags%2Cadmin_action_logs%2Cannouncement_mutes%2Cannouncement_reactions%2Cannouncements%2Cannual_report_statuses_per_ …
> feat: hidden nodes can now be reflected from query parameters

- frontend/.changeset/ninety-llamas-beam.md
- frontend/.changeset/slimy-cycles-press.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx
- frontend/packages/erd-core/src/features/gtm/utils/index.ts
- frontend/packages/erd-core/src/features/gtm/utils/toggleLogEvent.ts
I have implemented a feature to send toggle logs when showing/hiding the Left Pane and displaying/hiding the Table.
| toggle LeftPane |
|--------|
| <video src="https://github.com/user-attachments/assets/8838f732-b964-4310-9f13-2f92871c84c0" /> |
| toggle TableName |
|--------|
| <video src="https://github.com/user-attachments/assets/93bad96c-f79c-4cc7-b593-2026e6d4cb38" /> |
> 📈: integrate toggle logging for sidebar and visibility button actions

- frontend/.changeset/dry-islands-flash.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/features/gtm/utils/index.ts
- frontend/packages/erd-core/src/features/gtm/utils/openRelatedTablesLogEvent.ts
Checked on Google Tag Assistant:
> 📈 : Add open related tables log event

- frontend/.changeset/dry-ligers-work.md
- frontend/.changeset/mean-rings-walk.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/NonRelatedTableGroupNode/NonRelatedTableGroupNode.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/NonRelatedTableGroupNode/NonRelatedTableGroupNode.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/NonRelatedTableGroupNode/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertElkNodesToNodes.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertNodesToElkNodes.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
I have grouped TableNodes without Relationships into a GroupNode, allowing a new layout definition to be applied. 
The new layout definition arranges the Nodes in a single vertical column.
| <img width="1489" alt="スクリーンショット 2024-12-19 17 36 17" src="https://github.com/user-attachments/assets/d4316eae-01c6-4e7b-8b8e-5a23c4084dda" /> | <img width="1489" alt="スクリーンショット 2024-12-19 17 35 54" src="https://github.com/user-attachments/assets/7ff016ef-7a79-4e12-a08a-7ee64d7b3660" /> |
> ✨ Grouping TableNodes without Relationships into a GroupNode and Applying a New Layout Definition

- frontend/.changeset/gentle-monkeys-remember.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.module.css
Remove unexpected cardinalities on initial loading.
https://github.com/user-attachments/assets/e8c46f9c-d8ad-41bf-a675-21a2ff47c7ff
https://github.com/user-attachments/assets/3769c4bd-588a-4956-a140-711a6ce266e8
> fix: Render CardinalityMarkers based on loading state

- .github/workflows/vercel-deploy-erd-sample.yml
- frontend/packages/cli/src/App.tsx
- frontend/packages/cli/vite-plugins/set-env.ts
- frontend/packages/erd-core/src/schemas/cliVersion/schemas.ts
Integrates the current envName(`production` or `preview`)   into the React component's environment variables.
There is no change to the visual behavior of the ERD HTML.
In local , make this diff
```diff
--- a/frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/ReleaseVersion.tsx
+++ b/frontend/packages/erd-core/src/components/ERDRenderer/AppBar/HelpButton/ReleaseVersion.tsx
@@ -5,6 +5,8 @@ import styles from './ReleaseVersion.module.css'
export const ReleaseVersion: FC = () => {
const { cliVersion } = useCliVersion()
+  console.log('cliVersion:', cliVersion)
+
// Example output for cliVersion:
// - Released version:
//   v0.0.11 (2024-12-19)
```
and `pnpm dev` , 
I found that `envName` set to `cliVersion`
> Set envName(`production` or `preview`) to cliVersion 

- frontend/.changeset/eighty-bottles-hope.md
- frontend/packages/erd-core/src/components/ERDRenderer/AppBar/CopyLinkButton/CopyLinkButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/FitviewButton/FitviewButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ZoomControls/ZoomControls.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx
- frontend/packages/erd-core/src/features/gtm/utils/clickLogEvent.ts
- frontend/packages/erd-core/src/features/gtm/utils/openRelatedTablesLogEvent.ts
- frontend/packages/erd-core/src/features/gtm/utils/repositionTableLogEvent.ts
- frontend/packages/erd-core/src/features/gtm/utils/selectTableLogEvent.ts
- frontend/packages/erd-core/src/features/gtm/utils/toggleLogEvent.ts
- frontend/packages/erd-core/src/features/gtm/utils/toolbarActionLogEvent.ts
Add ``cliVer`` parameter to log event functions and components.
> 📈 Add cliVer parameter to log event functions and components

- frontend/.changeset/calm-books-occur.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/TidyUpButton/TidyUpButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
There is a problem with not highlighting when opening with a URL with query parameters.
In handleLayout, changed to take nodes as arguments.
This PR does not change the behavior. 
In the next PR, we plan to calculate the highlight information and pass it to nodes.
> refactor: Update handleLayout to accept nodes and improve hidden node handling

- frontend/.changeset/thirty-cats-smash.md
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
https://github.com/user-attachments/assets/95ec6652-e061-460b-81a3-439d0504ea44
> fix: Fixed problem with active tables not being highlighted in LeftPane when opened via query parameter

- frontend/.changeset/gold-singers-move.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.tsx
Each of the unnecessary logic was removed.
> refactor: Remove unused isRelatedToTable function and simplify TableNode component logic

- frontend/.changeset/breezy-pianos-listen.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Comment/Comment.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/ShowModeMenu/ShowModeMenu.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Toolbar/Toolbar.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
- frontend/packages/ui/src/styles/variables.css
Fully applied the `Inter` font-family throughout.
safari:
1. 9065d33a: Update web font URL to include `Inter`.
2. 4aa18afa: Update `font-family` setting in `src/components/ERDRenderer/**/*`.
3. 381c3ae4: Apply global `font-family` settings to Radix-originated toolbar.
4. a3fed344: Apply `font-family` settings to Vaul-originated drawer.
5. 28a9eb22: Add .changeset markdown.
Changes `3.` and `4.` were necessary due to the relatively higher DOM hierarchy of the Toolbar and Drawer within `src/components/ERDRenderer`, requiring specific adjustments for these components. For change `3`, I used a global setting. As noted in the CSS comments, I heavily referenced the information from Radix's issue [https://github.com/radix-ui/primitives/issues/2908](https://github.com/radix-ui/primitives/issues/29 …
> :lipstick: Update `font-family` settings across ERD Renderer components

- frontend/.changeset/fair-mayflies-exist.md
- frontend/packages/ui/src/markers/CardinalityZeroOrManyLeftMarker.tsx
- frontend/packages/ui/src/markers/CardinalityZeroOrOneLeftMarker.tsx
- frontend/packages/ui/src/markers/CardinalityZeroOrOneRightMarker.tsx
I've resolved the problem of the missing toolbar on mobile browsers.
Preview: https://liam-erd-sample-acagd5sze-route-06-core.vercel.app/
| device/browser | Before  | After |
| ------------- | ------------- | ------------- |
| iPhoneSE<br>(Safari) |  ![IMG_0083](https://github.com/user-attachments/assets/40fdcec7-4f7a-4b30-959c-0c3a8ff3c169) | ![IMG_0082](https://github.com/user-attachments/assets/d0af85f3-2e77-4ec9-917a-e18c5e950247)  |
| Android<br>(Chrome) | ![Screenshot_2024-12-23-15-12-26-15_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/63578c2a-95b0-45cc-a896-7eaab37f49e0) | ![Screenshot_2024-12-23-15-04-34-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/a646cb2e-c086-45c1-a1bd-9f5f14aace9a)  |
I've checked on Firefox🔥 …
> ⚒️ Adjust the appearance of the toolbar on mobile devices

- frontend/.changeset/warm-suits-love.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.module.css
**There was error when compiling on Next.js:**
```
Parsing css source code failed
Selector is not pure (pure selectors must contain at least one local class or id), (lightningcss, Selector(marker, specificity = 0x1))
```
**This error means:**
In CSS Modules, “selectors that do not contain local classes or IDs” will result in an error, so if you write an element selector like this marker { ... } as is, you will get the following error } as it is, the following error will occur.
**Solution:**
Edge markers have different IDs depending on whether they are highlighted or not. Changing the color is implemented by replacing the SVG element because the color of markers can not be dynamically changed by CSS. Therefore, this CSS was not actually applied. Currently it is difficult to make the …
> fix: Update css module for edge marker

- frontend/.changeset/angry-ravens-greet.md
- frontend/.changeset/eleven-islands-buy.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.test.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/highlightNodesAndEdges.ts
Drawing multiple strokes with stroke-dasharray specified causes performance degradation, especially in Safari browser.
Therefore, I stopped using stroke-dasharray.
Additionally, since stroke-dasharray is also used when 'animated' is set to true in Edge, I made sure that 'animated' is always set to false.
Furthermore, since setting 'animated' to false made it difficult to visually distinguish the flow of Edges, I used animateMotion instead to express Edge animations.
| <video src="https://github.com/user-attachments/assets/17596874-3c80-4a18-99dd-2e58bdcb7c0c" /> | <video src="https://github.com/user-attachments/assets/f8420ee8-edd5-4251-ad4c-1a1b1796375f" /> |
> 🚸 Add animated particles to highlighted relationship edges

- .changeset/dirty-crabs-happen.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Comment/Comment.tsx
fix: Comment component to use `<span>` instead of `<p>`
closes https://github.com/liam-hq/liam/issues/370
`<p>` nesting exists.
> :bug: fix: Comment component to use `<span>` instead of `<p>`

- frontend/apps/docs/app/layout.config.tsx
- frontend/apps/docs/content/docs/index.mdx
- frontend/apps/docs/content/docs/static-build/drizzle.mdx
- frontend/apps/docs/content/docs/static-build/index.mdx
- frontend/apps/docs/content/docs/static-build/postgresql.mdx
- frontend/apps/docs/content/docs/static-build/prisma.mdx
- frontend/apps/docs/content/docs/static-build/rails.mdx
- frontend/apps/docs/package.json
- pnpm-lock.yaml
Only the top page was seriously rewritten.
- **🔧 Add lucide-react dependency to package.json**
- **🔧 Add 'Roadmap' link to layout configuration**
- **docs: re-write the docs index page**
> docs: rewrite top page for first release

- .changeset/cyan-donkeys-design.md
- frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
- ref: https://github.com/liam-hq/liam/discussions/376
|before|after|
| --- | --- |
| <img width="1544" alt="スクリーンショット_2024-12-25_11_47_46" src="https://github.com/user-attachments/assets/b935a1ad-4a14-42d7-bf1e-7a650c0161d6" /> | <img width="1544" alt="スクリーンショット_2024-12-25_11_49_06" src="https://github.com/user-attachments/assets/0b6e872b-49dc-4bac-9ed5-fe7f1bd383f8" /> |
> style: Eliminate overlap between sidebar rail and scrollbar

- .changeset/tall-donuts-swim.md
- frontend/packages/db-structure/.gitignore
- frontend/packages/db-structure/package.json
- frontend/packages/db-structure/src/parser/schemarb/loadPrism.ts
- frontend/packages/db-structure/src/parser/schemarb/parser.ts
Fix compatibility issue with Node.js v18 in ERD tool
Addresses a compatibility issue with Node.js v18 that causes the following error when running the command:
```
$ npx @liam-hq/cli erd build --input path/to/schema.rb --format schemarb
```
```
Error: Failed to parse schemarb file: wasi.getImportObject is not a function
```
confirmed v18 test passed in GitHub Actions.
test commit: https://github.com/liam-hq/liam/pull/380/commits/9c298703d3c0b6a1b7b6681d771714fb2475f087
CI: https://github.com/liam-hq/liam/actions/runs/12491595523/job/34857812861
> :bug: Fix compatibility issue with Node.js v18 in ERD tool

- .changeset/spicy-donkeys-wink.md
- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
- frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
- frontend/packages/cli/src/App.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
The web version has been modified to take cookies out of Node.js for SSR.
Sidebar remains open when reloading with sidebar open ✅ 
https://github.com/user-attachments/assets/9b045021-7efc-4343-a62f-ce708005f5f1
ref: https://liam-erd-7b18wh3x2-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/ekylibre/ekylibre/refs/heads/main/db/structure.sql
> fix: Fixed an issue where sidebar state could not be set from cookie in web version

- .changeset/khaki-pandas-shout.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/RelationshipEdgeParticleMarker/RelationshipEdgeParticleMarker.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/RelationshipEdgeParticleMarker/RelationshipEdgeParticleMarker.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/RelationshipEdgeParticleMarker/index.ts
I fixed an issue where particles used in RelationshipEdge were not being rendered.
(Similar issue to this https://github.com/liam-hq/liam/pull/387)
| <video src="https://github.com/user-attachments/assets/f3fad75c-eebc-4f73-8519-e3d645ed40ad" /> |<video src="https://github.com/user-attachments/assets/163566a6-c1bf-4b4b-861f-271d85116ed0" /> |
> 🐛 : move RelationshipEdgeParticleMarker for gradient rendering to ERDRenderer

- .changeset/soft-crabs-begin.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
I fixed it so that cardinality is also displayed in Table Name mode.
| ![image](https://github.com/user-attachments/assets/1c1065f4-e0eb-441a-9599-6b7d3dc1f4dd) | ![image](https://github.com/user-attachments/assets/cf36e0fa-1285-4900-b01e-c63260adc369) |
> 🐛 update TableHeader styles and add handle positioning for connections

- .changeset/nervous-eyes-check.md
- frontend/apps/erd-web/.gitignore
- frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
- frontend/apps/erd-web/next.config.ts
- frontend/apps/erd-web/package.json
- frontend/packages/db-structure/src/parser.ts
- frontend/packages/db-structure/src/parser/index.ts
- frontend/packages/db-structure/src/parser/schemarb/index.ts
- frontend/packages/db-structure/src/parser/schemarb/loadPrism.ts
- turbo.json
Schema.rb format files can now be opened 👍🏻 
https://liam-erd-de01oyuvp-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/mastodon/mastodon/877090518682b6c77ba9bdfa0231afd56daec44d/db/schema.rb
> web: support schema.rb for rendering ER diagrams

- .changeset/config.json
Currently, even for applications that are not version controlled, versions have been updated.
ref: https://github.com/liam-hq/liam/pull/382
Ignored packages that are not version controlled.
You can check the `Version Packages` PR behavior at hand with `pnpm changeset version`.
> :wrench: Update changeset config to ignore specific packages

- .changeset/breezy-olives-decide.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useSyncHiddenNodesChange.ts
- frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
1. Select any TableNode 
1. Click “Open in main area” under Related Tables in TableDetail 1.
1. Click “Tidy Up”, the layout will be adjusted and fitView() will be executed, but it will be drawn at the top of the screen
| demo |
|--------|
| <video src="https://github.com/user-attachments/assets/d46ee707-7f4e-404b-9e80-55e47ed2bc14" /> | 
The transparent nonRelatedTableGroup remained and was fitViewed including its display area.
If all the nodes whose parentId is nonRelatedTableGroup node are hidden, the nonRelatedTableGroup node is also hidden.
https://github.com/user-attachments/assets/23ad41ab-738f-49a3-ba84-681223b2d792
> :bug: Fixed problem with fitView not working properly while displaying only some tables

- frontend/packages/cli/src/cli/index.ts
This is without .changeset, I think that is ok.
Improve `erd build` option description
```
[liam]$ cd frontend/packages/cli
```
```
[cli]$ node dist-cli/bin/cli.js erd build --help
(node:61123) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Usage: liam erd build [options]
Build ERD html assets
Options:
--input <path|url>  Path or URL to the .sql file
--format <format>   Format of the input file (postgres|schemarb)
-h, --help          display help for command
```
> Improve `erd build` option description

- frontend/apps/docs/app/docs/sitemap.ts
- frontend/apps/docs/public/robots.txt
Accessing https://liambx.com/docs routes the path to https://liam-docs-sigma.vercel.app/docs.
| repository | service-site | liam-hq/liam| 
| --- | --- | --- |
| URL |  https://liambx.com/ |  https://liam-docs-sigma.vercel.app| 
| Crawl |  ⭕️ |  ❌| 
| sitemap | has own sitemap<br>and refer to  https://liambx.com/docs/sitemap.xml | has own sitemap (/docs) |
This time, I created a sitemap for https://liam-docs-sigma.vercel.app/docs.
preview(sitemap): https://liam-docs-7tfe1sai4-route-06-core.vercel.app/docs/sitemap.xml
I don't think a ``changeset`` is needed for this change, but please let me know if I'm mistaken🙏.
> 📘 Add robots.txt and sitemap to docs

- frontend/apps/erd-web/next.config.ts
- frontend/packages/cli/biome.jsonc
- frontend/packages/configs/biome.jsonc
- frontend/packages/db-structure/biome.jsonc
- frontend/packages/erd-core/biome.jsonc
- frontend/packages/figma-to-css-variables/biome.jsonc
:wrench: Adjust biome rule`lint/correctness/noNodejsModules` setting
closes #401
> :hammer: Adjust biome rule`lint/correctness/noNodejsModules` setting

- frontend/apps/erd-web/next.config.ts
Adjust `assetPrefix` configuration for non-production environments
- Set `assetPrefix` to `undefined` when `NEXT_PUBLIC_ENV_NAME` is not 'production'.
- The path `/erd/p/raw.githubusercontent.com/{owner_name/repo_name}/refs/heads/main/db/structure.sql`  is worked **in vercel preview environment(note: that is private for liam-dev)**.
- check https://liam-erd-fze3tb8u5-route-06-core.vercel.app/
No Changeset setting. Intentionally.
> Adjust `assetPrefix` configuration for non-production environments

- .changeset/clever-pens-invite.md
- frontend/packages/cli/src/cli/actionRunner.ts
- frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
- frontend/packages/cli/src/cli/erdCommand/index.test.ts
- frontend/packages/cli/src/cli/erdCommand/index.ts
- frontend/packages/cli/src/cli/erdCommand/runPreprocess.test.ts
- frontend/packages/cli/src/cli/erdCommand/runPreprocess.ts
- frontend/packages/cli/src/cli/errors.ts
- Output logs are now prefixed with `ERROR:` and `WARN:` and output in color.
- In case of `ERROR` exit 1.
```sh
node dist-cli/bin/cli.js erd build --format postgres --input https://raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
```
output
> :sparkle: Improved error output

- .changeset/nasty-taxis-agree.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
This update addresses auto-layout issues, particularly in the following scenarios:
- HTML generated by `liam erd build`
- Mitigates a common problem observed in Safari
- Likely does not fully prevent the issue yet 🙏 
- Problems in `apps/erd-web`
- <details><summary>screenshot</summary>
https://liam-erd-web.vercel.app/erd/p/raw.githubusercontent.com/mastodon/mastodon/refs/heads/main/db/schema.rb
</details>
The use of `window.requestAnimationFrame` aligns with practices demonstrated in React Flow examples.
Reference: https://reactflow.dev/learn/layouting/layouting
- **This PR**: [Preview](https://liam-erd-91eq87lg9-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/mastodon/mastodon/refs/heads/main/db/schema.rb)
- **Main Branch**: …
> 🐛 Apply `window.requestAnimationFrame` to resolve conflicts between auto-layout and fitView operations

- .changeset/large-waves-hug.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/usePopStateListener.ts
- frontend/packages/erd-core/src/stores/userEditing/actions.ts
- frontend/packages/erd-core/src/stores/userEditing/store.ts
* [♻️ refactor: Rename isPopstateNavigation to isPopstateInProgress](https://github.com/liam-hq/liam/commit/b57ada9a29f9d69f5aff39ff0d562409e96a9264)
* Navigation is not very clear meaning, so it makes clear that the popstate operation is in progress.
* [♻️ refactor: Delete argument form updateActiveTableName](https://github.com/liam-hq/liam/commit/e04b84a2777980de14d002322c4bd1bc6edbea13)
* If each update actions accept args (`isPopstateInProgress`), e.g. `replaceHiddenNodeIds `, the amount of code increases and becomes complex.
* [♻️ refactor: Manage state in usePopStateListener](https://github.com/liam-hq/liam/commit/6a377154260466abb3c67c4ff43afad552c3b9d2)
* Prevent adobe problem by having an action to update `isPopstateInProgress`.
> ♻️ Refactor usePopStateListener

- .github/workflows/vercel-deploy-erd.yml
- .github/workflows/vercel-deploy.yml
Enabled `apps/erd-web` to deploy to the preview environment even when a PR contains changes only under `packages/`.
- Renamed `.github/workflows/vercel-deploy-erd-sample.yml` to `.github/workflows/vercel-deploy-erd.yml` to encompass both `erd-sample` and `erd-web` deployments.
- Updated filters in `vercel-deploy-erd.yml` to include `erd-web` sources.
- Added `erd-web` configuration to the deployment job in `vercel-deploy-erd.yml`.
GitHub Actions in this PR are worked
- apps/docs
- apps/erd-web
- apps/erd-sample
No changeset added intentionally.
> Refactor workflows to include `erd-web` deployment

- .changeset/beige-clocks-deliver.md
- frontend/apps/erd-web/app/globals.css
- frontend/apps/erd-web/tsconfig.json
- frontend/packages/ui/src/styles/fonts.css
- frontend/packages/ui/src/styles/globals.css
- frontend/packages/ui/src/styles/variables.css
- Moved `@import` rule for Google Fonts to resolve an error in Chrome.
- Addressed an issue in Safari where the font incorrectly appeared as serif.
- **erd-sample**
- Visit https://liam-erd-sample-t04r56gms-route-06-core.vercel.app/  by Safari
- **erd-web**
- Visit https://liam-erd-eyqd2fas5-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/mastodon/mastodon/refs/heads/main/db/schema.rb by Safari
> 🐛 Fix CSS import issue and improve font handling in `erd-web`

- frontend/apps/erd-web/app/erd/galaxy/page.tsx
- frontend/apps/erd-web/app/erd/page.tsx
- frontend/apps/erd-web/app/page.tsx
a new page component has been added to handle the ``/erd/galaxy`` URL. The component includes logic to display the page only in non-production environments. 
If the environment is set to production, the page will return a 404 Not Found response.
As far as I understand...↓
URL | local | preview | production
-- | -- | -- | --
/ | redirect to /erd/galaxy | redirect to /erd/galaxy | access service-site
/erd | redirect to /erd/galaxy | redirect to /erd/galaxy | return 404
/erd/galaxy | access the /erd/galaxy | access the /erd/galaxy | return 404
If I'm mistaken, please let me know. 🙏
> ✨ Add a new galaxy page and implement a redirect from the ERD page

- .changeset/hip-poems-trade.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
A minor fix. The **small margin on the right and bottom** of the LeftPane on mobile devices, caused by the Toolbar, has been removed.
preview: https://liam-erd-sample-r58kkhgx5-route-06-core.vercel.app/
> 🚸 delete unnecessary margin on mobile

- .changeset/tender-seas-cover.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
Move react flow attribution from bottom-right to bottom-left.
|before|after|
|--|--|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/a418576e-84d5-4781-83f9-2f2a5b1f2afa" />|<img width="300" alt="image" src="https://github.com/user-attachments/assets/ca8682d6-c6f6-49df-80a8-e72c8d5fab76" />|
Reason:
When embedding an ER diagram in an iframe in LP, we would like to display a link to go to the path of the ER diagram on bottom-right, but it overlaps with the React Flow logo (attribution).
> 💄 Move react flow attribution from bottom-right to bottom-left

- docs/packages-license.md
- frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
- frontend/apps/erd-web/package.json
- pnpm-lock.yaml
Refactored HTML title extraction to use `cheerio` for DOM parsing instead of regular expressions.
This enhances maintainability for future extensions.
ref: [hoshino-san comment](https://github.com/liam-hq/liam/pull/427#discussion_r1908232709)
https://www.npmjs.com/package/cheerio
The reason to chose `cheerio` over `jsdom` is that it is lightweight and faster for simple HTML parsing tasks like our usecases.
ref: https://www.zenrows.com/blog/jsdom-vs-cheerio
> ♻️ Add cheerio for HTML parsing in metadata extraction

- .changeset/afraid-apes-add.md
- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
- frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
- frontend/packages/db-structure/src/index.ts
- frontend/packages/db-structure/src/parser.ts
- frontend/packages/db-structure/src/parser/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay.tsx
Component for erd-web app.
- Introduced the `ErrorDisplay` component to provide a visual representation of errors in the ERD renderer.
display: 
https://liam-erd-ajtacqg7o-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
> 🚸 Add ErrorDisplay component for handling and displaying errors in ERDViewer (first step)

- README.md
I fixed a broken link to docs/packages-license.md in README.md.
none
fix a broken link 
check the link in [README.md](https://github.com/liam-hq/liam/blob/7c08f949596cc294133ccfb68cd110b52bf9b550/README.md)
> fix a broken link to docs/packages-license.md in README.md

- .changeset/wild-crews-battle.md
- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
- frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
- frontend/packages/cli/src/cli/erdCommand/runPreprocess.test.ts
- frontend/packages/cli/src/cli/erdCommand/runPreprocess.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay.tsx
Enhanced error rendering in the `ErrorDisplay` component, adding detailed error summaries.
- Replaced `ProcessError` with `ErrorObject` across components and modules.
- Fixed typos in error messages, replacing "parcing" with "parsing" in test files and logic.
Now 
You can check the differrence:
* main branch: 
* https://liam-erd-web.vercel.app/erd/p/raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
* this PR branch:
* preview: https://liam-erd-2hxkzepwq-route-06-core.vercel.app/erd/p/raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql
* or local: http://localhost:3001/erd/p/raw.githubusercontent.com/metabase/metaba …
> 🚸 Enhanced error rendering in the ErrorDisplay component, adding detailed error summaries

- frontend/apps/docs/app/docs/llms-full.txt/route.ts
https://liam-docs-jpgj8xmww-route-06-core.vercel.app/docs/llms-full.txt
As `liambx.com/docs/llms-full.txt`, I have created an endpoint that returns the entire manual content in a single markdown plain/text format. Our objectives are twofold:
1. for use by the dev team in product development
- 2. to pass all information in the manual to LLM and make it easier to discuss Liam ERD
- ref: [started providing llms-full.txt on this site | Hirotaka Miyagi](https://www.mh4gf.dev/articles/llms-full-txt)
2. marketing purposes to be put on https://llmstxt.site/
> ✨ Add static route to serve concatenated MDX content from docs directory

- .changeset/olive-spoons-notice.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/usePopStateListener.ts
- frontend/packages/erd-core/src/schemas/queryParam/schemas.ts
- frontend/packages/erd-core/src/stores/userEditing/store.ts
In thisPR, the code has been updated to manage the ``showMode`` state and synchronize it with the URL query parameters.
Preview: https://liam-erd-sample-ggnkr3clv-route-06-core.vercel.app/?showMode=TABLE_NAME&active=status_edits
close: https://github.com/liam-hq/liam/issues/337
The  ``showMode`` state is now monitored, and any changes to it are reflected in the URL query parameters.
A  ``previousShowMode`` variable is used to track the previous state and detect changes.
When  ``showMode`` changes, the URL query parameter  ``showMode`` is updated accordingly.
If showMode is set, it is added to the URL; otherwise, it is removed.
> ✨ Implement show mode handling in URL parameters and state management

- .github/workflows/discussion-comment-to-slack.yml
> 🔧: add GitHub Actions workflow to send discussion comments to Slack

- frontend/apps/docs/app/global.css
- frontend/apps/docs/tailwind.config.js
I added fumadocs color themes and Tailwind color themes to match the design of the docs site.
| light | dark |
| ![スクリーンショット 2025-01-15 17 58 42](https://github.com/user-attachments/assets/9997c337-1839-43bc-8f69-5268383ad175) | ![スクリーンショット 2025-01-15 17 58 32](https://github.com/user-attachments/assets/ad4c7a6d-847d-4254-bc11-56068e02e545) |
> 💄 Add custom color theme settings

- frontend/apps/erd-web/package.json
Removed `--turbopack` flag from the dev script as it may bypass webpack configurations defined in `next.config.ts`, specifically our webpack alias settings for `@prisma/internals`. This ensures consistent behavior between development and production environments.
>Note: Production builds with next build are not yet supported.
https://turbo.build/pack/docs
- https://github.com/liam-hq/liam/pull/454
> 🔧 Disable turbopack option from dev command for ERD Web

- frontend/apps/docs/app/docs/[[...slug]]/page.tsx
- frontend/apps/docs/biome.jsonc
- frontend/apps/docs/components/Tabs/Tabs.tsx
- frontend/apps/docs/components/Tabs/index.ts
- frontend/apps/docs/components/index.ts
- frontend/apps/docs/content/docs/debug.mdx
To change the background color of TabsList, I used original Tabs/Tab components instead of the ones from fumadocs-ui/components/tabs.
| ![スクリーンショット 2025-01-16 18 17 23](https://github.com/user-attachments/assets/f5370529-2a1d-4f42-982c-ade47d7c1a53) | ![スクリーンショット 2025-01-16 18 17 05](https://github.com/user-attachments/assets/8f0d4893-dde5-4ef8-8c97-ae1e06856d23) | 
- [Tabs - Fumadocs](https://fumadocs.vercel.app/docs/ui/components/tabs#advanced)
> ✨ Create original Tabs/Tab component for docs

- docs/packages-license.md
- frontend/apps/docs/app/docs/[[...slug]]/page.tsx
- frontend/apps/docs/app/global.css
- frontend/apps/docs/components/Callout/Callout.tsx
- frontend/apps/docs/components/Callout/index.ts
- frontend/apps/docs/components/index.ts
- frontend/apps/docs/package.json
- frontend/apps/docs/tailwind.config.js
- frontend/packages/ui/src/icons/index.ts
- pnpm-lock.yaml
I added a Callout component for use in MDX documents.
* [➕ add ts-pattern, tailwind-variants, @liam-hq/ui](https://github.com/liam-hq/liam/pull/483/commits/129673264f49f9fd22170a1cdbae0122550cfbfc)
* I added the necessary dependencies to implement the Callout component.
* [💄 Enhance Tailwind CSS configuration with new color variables.](https://github.com/liam-hq/liam/pull/483/commits/8d7aa8a939e9438c893dcf3a332887c8ed54a417)
* I added the necessary color definitions to implement the Callout component.
* [✨ Add Callout component](https://github.com/liam-hq/liam/pull/483/commits/4b280bfef1dc67d3e58ec6ea65c25157a18debf5)
* I implemented the Callout component.
* I made sure the component's props match those provided by the Fumadocs Callout component.
- [Callout | …
> ✨ Add Callout component

- frontend/apps/docs/app/docs/[[...slug]]/page.tsx
- frontend/apps/docs/biome.jsonc
- frontend/apps/docs/components/Heading/Heading.tsx
- frontend/apps/docs/components/Heading/index.ts
- frontend/apps/docs/components/index.ts
- frontend/apps/docs/content/docs/debug.mdx
I created an original Heading component with adjustable font sizes from the Heading provided by Fumadocs.
| light | dark |
| <img width="604" alt="スクリーンショット 2025-01-17 14 42 43" src="https://github.com/user-attachments/assets/315d585e-25b2-4b2c-a4d7-2e2257c0ceae" /> | <img width="602" alt="スクリーンショット 2025-01-17 14 42 51" src="https://github.com/user-attachments/assets/7dc84d37-52cb-458c-91e1-6430feb0bf00" /> | 
- [Heading | Fumadocs](https://fumadocs.vercel.app/docs/ui/mdx/heading)
> ✨ Introduce Heading component

- frontend/apps/docs/app/docs/[[...slug]]/page.tsx
- frontend/apps/docs/components/Breadcrumb/Breadcrumb.tsx
- frontend/apps/docs/components/Breadcrumb/index.ts
- frontend/apps/docs/components/index.ts
I created an original Breadcrumb component with adjustable font size, weights and color, and replaced the default breadcrumb used within Fumadocs with it.
| light | dark |
| <img width="603" alt="スクリーンショット 2025-01-17 14 50 01" src="https://github.com/user-attachments/assets/66e3d3ee-0087-42f6-84e1-3cf028466846" /> | <img width="601" alt="スクリーンショット 2025-01-17 14 49 54" src="https://github.com/user-attachments/assets/1dc36288-3d8b-4b8d-84a3-d639dcc69d7d" /> | 
- [Page#Breadcrumb | Fumadocs](https://fumadocs.vercel.app/docs/ui/layouts/page#breadcrumb)
> ✨ Add Breadcrumb component for original style

- .github/workflows/frontend-ci.yml
- .github/workflows/license.yml
- .github/workflows/vercel-deploy-erd.yml
- .github/workflows/vercel-deploy.yml
I have already changed the `GITHUB_TOKEN` permissions to read-only at the organizational level. This follows the [Principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege).
In this pull request, I will make changes to workflows that should clearly be granted permissions.
Since all the tests in this pull request have passed, I think it is ok. If permissions-related problems occur in the future, we can deal with them on a case-by-case basis.
> Add permissions to the GitHub Actions workflows

- frontend/apps/docs/app/docs/[[...slug]]/page.tsx
- frontend/apps/docs/components/Breadcrumb/Breadcrumb.tsx
- frontend/apps/docs/components/FooterNavi/FooterNavi.tsx
- frontend/apps/docs/components/FooterNavi/index.ts
- frontend/apps/docs/components/index.ts
I created an original FooterNavi component with adjusted hover colors, and replaced the default footer used within Fumadocs with it.
| light | dark |
| <img width="863" alt="スクリーンショット 2025-01-17 15 34 53" src="https://github.com/user-attachments/assets/67e210e5-71c7-4d0d-8714-e7031971105a" /> | <img width="864" alt="スクリーンショット 2025-01-17 15 34 37" src="https://github.com/user-attachments/assets/776c2a92-aaeb-4b48-bd60-a34237475cef" /> | 
- [Page#Footer | Fumadocs](https://fumadocs.vercel.app/docs/ui/layouts/page#footer)
> ✨ Add FooterNavi component for original style

- .changeset/fast-penguins-call.md
- frontend/packages/cli/src/cli/actionRunner.ts
- frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
- Updated `actionRunner` to exit with status 1 if there is at least one error, matching the behavior of `buildCommand`.
- Added a comment explaining the future plan to allow successful execution with warnings for minor errors.
- Clarified that in the future, only `CriticalError` should trigger an exit with status 1.
```
[liam]$ npx @liam-hq/cli@latest erd build --input https://raw.githubusercontent.com/metabase/metabase/fe13ca685912aa3cde89a7a7e8c0d4698cf9d060/resources/migrations/initialization/metabase_mysql.sql --format postgres
Need to install the following packages:
@liam-hq/cli@0.0.24
Ok to proceed? (y) y
WARN: Error during parsing schema file: syntax error at or near "="
WARN: Error during parsing schema file: syntax error at or near "`"
[liam]$ echo $?
0
```
```
[cli]$ node …
```
> 🐛 Update `erd build` to exit with status 1 if there is at least one error

- frontend/apps/erd-web/next.config.ts
- frontend/apps/erd-web/scripts/install-prisma-internals.mjs
Exclude `@prisma/internals` from the bundle
to prevent `Error: Cannot find module 'fs'` errors in the build process.
✅ schema.rb
https://liam-erd-2e02911f4-route-06-core.vercel.app/erd/p/github.com/mastodon/mastodon/blob/main/db/schema.rb
✅ sql
https://liam-erd-2e02911f4-route-06-core.vercel.app/erd/p/github.com/ekylibre/ekylibre/blob/main/db/structure.sql
✅ Prisma 🎉
https://liam-erd-2e02911f4-route-06-core.vercel.app/erd/p/github.com/langfuse/langfuse/blob/main/packages/shared/prisma/schema.prisma
> 🔧 Update Next.js configuration to exclude '@prisma/internals'

- frontend/apps/docs/app/layout.tsx
- related: https://github.com/liam-hq/liam/pull/500
Add Banner with blog link 👾
ref: https://liam-docs-7bl6utmtf-route-06-core.vercel.app/docs
> ✨ Add Banner component to layout for Liam ERD launch announcement

- frontend/apps/docs/app/global.css
I've resolved the mobile design issues. I've removed the global ``--fd-sidebar-width`` setting and reverted it to the default ``260px``. Since the sidebar was designed with a width of ``260px``, this should address the problem.
| Before  | After |
| ------------- | ------------- |
| ![ss 2728](https://github.com/user-attachments/assets/60050b49-e1d6-4a43-b5f6-039e72b55366) | ![ss 2727](https://github.com/user-attachments/assets/960e400c-a641-4d10-bcda-d4f5a5f59d3c) |
https://liam-docs-rokwzylu4-route-06-core.vercel.app/docs
> 🐛 docs: Modifying styles for mobile devices

- frontend/apps/docs/components/Banner/JackAnimationForDark.tsx
We're encountering an issue where Mr. Jack is not showing up on https://liambx.com/docs. 
The problem lies in the riv file, which is currently referencing ``https://liambx.com/rivs`` instead of the correct path ``https://liam-docs-sigma.vercel.app/rivs``. To fix this, I've updated the source to use an absolute path. While I can't verify this until after deployment, I expect that this change will resolve the display issue.
> 🐛 Change the Rive src attribute to an absolute path.

- .changeset/yellow-rocks-run.md
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
Add support for table comments in Prisma schema.
> [!NOTE]
>Prisma does not yet support table and column comments.
> - https://github.com/prisma/prisma/issues/8703
>I mean, Prisma comment feature is only attached within the AST and is not applied to user database.
> ```js
> /// This comment will get attached to the `User` node in the AST
> model User {
>   /// This comment will get attached to the `id` node in the AST
>   id     Int   @default(autoincrement())
>   // This comment is just for you
>   weight Float /// This comment gets attached to the `weight` node
> }
> ```
> https://www.prisma.io/docs/orm/prisma-schema/overview#comments
> ✨ Add support for table comments in Prisma schema

- frontend/packages/db-structure/src/parser/prisma/index.test.ts
There are several type attributes supported by specific db engine such as `@db.BigInt`.
ref: https://www.prisma.io/docs/orm/reference/prisma-schema-reference#model-field-scalar-types
If we use default connector, these attributes will raise validation error:
```ts
GetDmmfError: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: Native type BigInt is not supported for Default connector.
-->  schema.prisma:6
| 
5 |         model users {
6 |           id   BigInt    @id @db.BigInt @default(autoincrement())
| 
```
So I've added the postgresql provider on each test cases.
ref: https://www.prisma.io/docs/orm/overview/databases/postgresql
> 📝 Add prisma schema header to tests for improved parsing validation

- .changeset/proud-cycles-train.md
- frontend/packages/db-structure/package.json
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
- pnpm-lock.yaml
Support parsing default values in Prisma schema
- Added `@prisma/generator-helper` as a dependency.
- for  `extractDefaultValue` return-type 
- Implemented `extractDefaultValue` function to correctly parse default values in Prisma models.
- Added test cases for parsing default values of type `String`, `Int`, and `Boolean`.
- erd-web works 
- preview: https://liam-erd-8a8524u0h-route-06-core.vercel.app/erd/p/github.com/langfuse/langfuse/blob/cf29c6b7e447cf1aec7a8d50ae6a877c3844b7cd/packages/shared/prisma/schema.prisma
> ✨️  Support parsing default values in Prisma schema 

- .changeset/curvy-bottles-obey.md
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
Exclude model type from columns
| before | after |
| <img width="635" alt="before" src="https://github.com/user-attachments/assets/b3b78581-449d-4a8b-bce1-513cfd203c2e" />  | <img width="510" alt="after" src="https://github.com/user-attachments/assets/b8b30e49-b944-4a0e-9840-01de2d15aba8" /> |
see preview https://liam-erd-o43orap6s-route-06-core.vercel.app/erd/p/github.com/langfuse/langfuse/blob/cf29c6b7e447cf1aec7a8d50ae6a877c3844b7cd/packages/shared/prisma/schema.prisma
> 🐛 fix: exclude model type from columns in Prisma parser 

- frontend/apps/docs/components/Banner/JackAnimationForLight.tsx
We previously encountered an issue where Mr. Jack was not being displayed. This was resolved in pull request #528.
While that PR only addressed **JackAnimationForDark**, we've now made the same fix for **JackAnimationForLight** as well.
（As **JackAnimationForLight** is not currently in use, we are unable to verify its functionality at this time.）
> 🐛 Change the Rive src attribute to an absolute path.(light ver)

- .changeset/perfect-bottles-know.md
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
Supported on delete fk constraint in Prisma parser.
Supported `relationOnDelete` only.
`relationOnUpdate` is not supported for now.
It was merged 10 days ago, and will be released `@prisma/generator-helper@6.3.0`.
- https://github.com/prisma/prisma/pull/26074
- https://github.com/prisma/prisma/milestone/144
> ✨ Support on delete fk constraint in Prisma parser

- frontend/apps/docs/content/docs/web.mdx
I fixed the URL that leads to supported-formats.👍
✔️ https://liambx.com/docs/parser/supported-formats
Preview: https://liam-docs-5z3170sjv-route-06-core.vercel.app/docs/web
> 🐛 docs: fix link to supported formats documentation

- .changeset/bright-shoes-look.md
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
Support index for Prisma parser.
https://www.prisma.io/docs/orm/prisma-schema/data-model/indexes
I've checked the actual properties from prisma index/unique attributes.
```ts
model dogs {
id   Int    @id @default(autoincrement())
name String
@@index([name])
}
```
```sql
-- CreateIndex
CREATE INDEX "dogs_name_idx" ON "dogs"("name");
```
```ts
model posts {
id      Int    @id @default(autoincrement())
user    users  @relation(fields: [user_id], references: [id])
user_id Int    @unique
count   Int    @unique // added
}
```
```sql
-- CreateIndex
CREATE UNIQUE INDEX "posts_count_key" ON "posts"("count");
```
```ts
model Company {
id        BigInt  @id @db.BigInt @default(autoincrement())
number    BigInt
@@index([id, number])
}
```
```sql
-- CreateIndex
CREATE INDEX "Company_id_number_idx" ON …
```
> ✨ Support index for Prisma parser

- frontend/apps/docs/components/Banner/Banner.tsx
- frontend/apps/docs/components/Banner/JackAnimationForDark.tsx
- frontend/apps/docs/components/Banner/JackAnimationForLight.tsx
preview: https://liam-docs-mwmo3vfzs-route-06-core.vercel.app/docs
💄 apps/docs: adjust banner styles for better responsiveness
- Increased padding (`px-4 → px-8`) for improved layout spacing.
- Adjusted font sizes (`text-sm → text-[10px] sm:text-sm`) for better readability on small screens.
- Changed `fit: Cover` to `fit: Contain` in `JackAnimationForLight` and `JackAnimationForDark` to ensure proper scaling.
- Adjusted minimum width and height (`w-[1.875rem] → w-[20px] sm:w-[1.875rem]`) for consistent display across screen sizes.
- Reduced spacing between elements (`gap-6 → gap-4`) for a more compact layout.
375px: 
| when text is short  | when text is long |
|  <img width="377" alt="スクリーンショット 2025-01-22 21 04 39" …
> 💄 apps/docs: adjust banner styles for better responsiveness

- frontend/packages/cli/README.md
- Removed the old `preview` sub-command from `frontend/packages/cli/README.md`
- This change affects the documentation displayed on https://www.npmjs.com/package/@liam-hq/cli
> 🐛 Update cli/README: Remove outdated `preview` sub-command

- .changeset/heavy-badgers-laugh.md
- .changeset/olive-jars-press.md
- .changeset/wild-rabbits-itch.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableNode.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/convertNodesToElkNodes.ts
I fixed an issue where long column names and type names would overlap and become unreadable.
I took the approach of expanding the width of the TableNode until all column names and type names are fully displayed.
| ![スクリーンショット 2025-01-23 20 48 33](https://github.com/user-attachments/assets/9c79b301-3e98-4388-b1ab-614f1bda8652) | ![スクリーンショット 2025-01-23 20 48 45](https://github.com/user-attachments/assets/91348f5d-4f15-4f7a-bb06-d2415d790d57) |
N/A
* [🚸 Make node width variable to accommodate table/column name and type](https://github.com/liam-hq/liam/pull/548/commits/76bc7be04c3c9945dc9c0e0d21f005c5ed2cd3a8)
* I set the width of TableNode to "auto".
* [🚧 Prevent omission of TableColumn](https://github.com/liam-hq/liam/pull/548/commits/18e75a33134cbbfb98 …
> 🚸 Make node width variable to accommodate table/column name and type

- frontend/apps/docs/content/docs/parser/supported-formats/rails.mdx
> [!WARNING]
> we should merge first https://github.com/liam-hq/liam-erd-samples/pull/2
📝 docs: Add sample workflow link for rails7.0 or later + db/structure.sql pattern
preview : https://liam-docs-ehypascgo-route-06-core.vercel.app/docs/parser/supported-formats/rails
ref. https://github.com/liam-hq/liam-erd-samples/pull/2
> 📝 docs: Add sample workflow link for rails7.0 or later + db/structure.sql pattern

- frontend/apps/docs/app/global.css
The background color of the areas using the Fumadocs package-install component was inconsistent with the design. I've corrected it to match the design.
> 💄 Add an override for the Fumadocs `package installation` component.

- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
Added condition to check if ERD is rendered on iframe.
If on iframe, cookie consent component is not appeared.
Checked by manually:
|before|after|
|--|--|
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/d4300050-7aa1-4cfb-8c58-25232469b6f0" />|<img width="400" alt="image" src="https://github.com/user-attachments/assets/8d028eb5-7d71-4e56-b340-4452865701ad" />|
```html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>ERD Viewer Embed Example</title>
<style>
iframe {
width: 100%;
height: 100vh;
border: none;
}
body {
margin: 0;
padding: 0;
}
</style>
</head>
<body>
<iframe
src="http://localhost:3001/erd/p/github.com/langfuse/langfuse/blob/cf29c6b7e447cf1aec7a8d50ae6a8 …
```
> 🚸 Conditionally render CookieConsent based on iframe context

- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
Fixed `ReferenceError: window is not defined`.
```ts
⨯ ReferenceError: window is not defined
at window (app/erd/p/[...slug]/erdViewer.tsx:42:19)
40 |   }
41 |   const version = v.parse(versionSchema, versionData)
> 42 |   const isIframe = window !== window.parent
|                   ^
43 |
44 |   return (
45 |     <div style={{ height: '100vh' }}> {
digest: '999588878'
}
```
I've confirmed no error on my local environment ✅
> 🐛 fix iframe detection to avoid window defined error

- .changeset/three-beds-wave.md
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
I updated LiamERD to display PostgreSQL data types by referring to https://www.prisma.io/docs/orm/reference/prisma-schema-reference.
I've made it so that enum values are returned as ``enum`` types.
| Before  | After |
| ------------- | ------------- |
| <img width=300 src="https://github.com/user-attachments/assets/aa0a5fca-4308-44f8-b679-929b255cb187">  | <img width=300 src="https://github.com/user-attachments/assets/ab920bae-2a56-4439-8eec-f53029194312">  |
> 🔧 Update Prisma column types to match PostgreSQL standards

- frontend/apps/erd-sample/scripts/update_dist_content.mjs
I have removed the Google Tag Manager tag that was embedded to track how the beta version is being used.
> 📈 Remove Google Tag Manager

- .changeset/early-files-talk.md
- frontend/packages/cli/src/cli/erdCommand/runPreprocess.test.ts
- frontend/packages/cli/src/cli/index.test.ts
- frontend/packages/db-structure/src/parser/index.ts
- frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.test.ts
- frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.ts
- frontend/packages/db-structure/src/parser/supportedFormat/schema.ts
- frontend/packages/db-structure/src/parser/tbls/index.test.ts
- frontend/packages/db-structure/src/parser/tbls/index.ts
- frontend/packages/db-structure/src/parser/tbls/parser.ts
- Add initial tbls parser
- Add format for `schema.json`
https://liam-erd-b9jxja3n1-route-06-core.vercel.app/erd/p/github.com/k1LoW/tbls/blob/v1.81.0/sample/mysql/schema.json
```sh
$ ./dist-cli/bin/cli.js erd build --input https://github.com/k1LoW/tbls/blob/v1.81.0/sample/mysql/schema.json --format tbls
```
> ✨ Add initial tbls parser

- .changeset/funny-squids-yawn.md
- frontend/packages/db-structure/src/parser/prisma/convertToPostgresColumnType.ts
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
While our PR for #572 previously supported only the following columns, we've enhanced it to provide more accurate support. For example, we now support columns like ``serial``, ``uuid``, and ``time``
Support for added columns: 
```
char
varchar
bit
varbit
uuid
xml
inet
citext
smallint
smallserial
serial
oid
bigserial
real
money
timestamptz
date
time
timetz
json
```
You can find the UUID and serial number within the ``cal.com`` data schema.
Preview: https://liam-erd-ncg6vs35h-route-06-core.vercel.app/erd/p/github.com/calcom/cal.com/blob/main/packages/prisma/schema.prisma?showMode=ALL_FIELDS&active=EventType
> 🔧 prisma: Supports column data types more accurately

- .changeset/silver-mirrors-march.md
- frontend/packages/db-structure/src/parser/tbls/index.test.ts
- frontend/packages/db-structure/src/parser/tbls/parser.ts
Support relationship cardinality parsing for tbls schema.
preview:
https://liam-erd-2ykidk7y9-route-06-core.vercel.app/erd/p/github.com/k1LoW/tbls/blob/v1.81.0/sample/mysql/schema.json
> ✨ Support relationship cardinality parsing for tbls schema

- frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
- frontend/apps/erd-web/app/layout.tsx
Enable GTM and CookieConsent for production.
> [!NOTE]
> I would like to check if the tag are delivered correctly, so let me merge by myself.
> 🔧 Enable GTM and CookieConsent for production

- .changeset/nice-starfishes-collect.md
- frontend/packages/db-structure/src/parser/__tests__/testcase.ts
- frontend/packages/db-structure/src/parser/prisma/index.test.ts
- frontend/packages/db-structure/src/parser/prisma/parser.ts
- frontend/packages/db-structure/src/parser/schemarb/index.test.ts
- frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
To improve consistency, I've standardized the tests using a single test case. However, variations in parser behavior, like ``index names`` and ``default values``, necessitate the redefinition of ``userTable`` for each parser.
> ♻️ Add createParserTestCases function and update parser tests

- frontend/apps/docs/content/docs/parser/supported-formats/index.mdx
I've improved /docs/parser/supported-formats.
- `via database url` is not supported yet, so delete it.
- I thought it would be clearer to use the notation “web or CLI”, so I did.
> 📝 Update supported formats documentation with new support levels and workarounds

- .changeset/nice-kiwis-begin.md
- frontend/packages/db-structure/src/parser/tbls/index.test.ts
- frontend/packages/db-structure/src/parser/tbls/parser.ts
Added support for default values in the tbls parser.
Since ``tblsColumn.default`` in tbls's ``schema.json`` provides values like booleans and numbers as strings (e.g., ``'1'`` or ``'true'``), we have added processing to appropriately convert them to numbers or booleans before returning.
> ✨ Add support for default in `tbls` parser

- frontend/apps/docs/content/docs/parser/supported-formats/index.mdx
- frontend/apps/docs/content/docs/parser/supported-formats/mysql.mdx
- related: https://github.com/liam-hq/liam-erd-samples/pull/4
I wrote an example of mysql support using tbls.
> 📝 Add MySQL documentation with tbls integration guide

- frontend/apps/docs/content/docs/parser/supported-formats/prisma.mdx
Added documentation for the CLI command to generate ER diagrams when using multiple Prisma schema files, as it was not previously specified.
> 📝 docs: Add instructions for handling multiple Prisma schema files

- .changeset/cuddly-cars-cross.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.tsx
Since the size of the icon may be smaller than 16px, specify the minimum size.
before
after
> 💄Fixed icon size

- docs/adr/template.md
Introduce ADR Template to store architecture decisions.
> 📝 Add ADR template

- .changeset/dry-insects-help.md
- frontend/packages/cli/src/cli/initCommand/index.ts
- ref: https://github.com/liam-hq/liam/pull/608#discussion_r1933130228
Removed duplicate output ( `tbls out -t json -o schema.json` ).
```bash
node frontend/packages/cli/dist-cli/bin/cli.js init
👾  Welcome to the @liam-hq/cli setup process! 👾
This `init` subcommand will guide you interactively through the setup.
🌟 This init command is a work in progress! 🌟
We’re continuously improving it. Don’t forget to run `npx @liam-hq/cli init` after updates for the latest features.
💡 Have feedback? Share it with us!
Visit https://github.com/liam-hq/liam/discussions to submit ideas or report issues.
🌟️ Love Liam ERD? Help us grow by starring our GitHub repository:
https://github.com/liam-hq/liam
----
Now, let’s get started with setting up your Liam ERD project.
✔ Which Technology (database or ORM) are …
```
> ♻︎ Simplify tbls schema.json generation instructions

- .changeset/clean-owls-approve.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.tsx
- frontend/packages/ui/src/icons/ChevronUp.tsx
- frontend/packages/ui/src/icons/index.ts
I've added a toggle feature to each section of the ``TableDetailDrawer``. For now, I've implemented it only for the ``Columns`` section.（So that I can apply it to other sections after the review.）
Preview: https://liam-erd-sample-b9tglfoys-route-06-core.vercel.app/?active=announcements
https://github.com/user-attachments/assets/f97763a9-fadb-4073-b4d6-b959274fe3eb
In the future,
https://github.com/liam-hq/liam/pull/607/commits/aecb91a55e2b2b9516a70c6834f7be6d936ac6fe : ✨ Implement collapsible columns in ERD table detail view
https://github.com/liam-hq/liam/pull/607/commits/1a656aa24093125ca30be4d3fc11a0b4b4998c92 : ♻️ Unify the structure and style of each section within the TableDetailDrawer.
I'd like you to check out the animation part!
> Toggle function for sections within the ``TableDetailDrawer``

- frontend/apps/erd-web/app/page.tsx
To easily check the correctness of the ERD display, the redirect destination for `/` has been changed.
https://liam-erd-i4l9slvml-route-06-core.vercel.app
> 🔧 Update default ERD page redirect to Mastodon schema

- .changeset/quick-crabs-smile.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.tsx
In PR #607, we added a toggle feature to the Columns section. Now, we've extended this functionality to include all remaining sections: ``Indices``, ``Unique``, and ``RelatedTables``.
https://github.com/user-attachments/assets/04dbad17-77b0-4e1c-a726-89a949049925
Since the ｀``RelatedTable`` is fixed at the bottom, it may behave in the following way.
https://github.com/user-attachments/assets/3aea6007-0545-452c-964a-94641a9ad50a
> ✨  Add toggle function for all sections in TableDetailDrawer

- .changeset/quick-llamas-chew.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Columns/Columns.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Indices/Indices.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/Unique/Unique.module.css
For mobile devices, the ``RelatedTables`` are no longer fixed to the bottom but scroll along with the content.
The header of each section has also been made sticky on scroll.
Since there's a lot of duplicate code, I'll refactor it in the next PR.🙏
| Before  | After |
| ------------- | ------------- |
|  RelatedTables is fixed to the buttom ![ss 2790](https://github.com/user-attachments/assets/23b82b7d-fb25-4e61-b1ee-8f734a3de076) | RelatedTables is not fixed  ![ss 2791](https://github.com/user-attachments/assets/af8e18ea-f0d3-4002-90cf-ead9e5826783) |
| The section header is scrollable. ![ss 2793](https://github.com/user-attachments/assets/51e9f304-5661-4371-927e-a7566f3f6e72) | The section header is not scrollable. ![ss 2794](https://github.com/user-attachments/assets/87028075-8a18-4916-8 …
> 💄 Update styles for responsive design and sticky headers in TableDetail components

- .changeset/rotten-icons-try.md
- frontend/packages/erd-core/src/stores/userEditing/store.ts
I've added browser back/forward support for the Toolbar's showMode. Also, I've done some code refactoring.♻️
CLI Ver
https://github.com/user-attachments/assets/ae6175d7-527c-45b3-906b-2c68582fb5a7
Web Ver
https://github.com/user-attachments/assets/1614186f-4f8d-4f3c-828d-2ee8379a5439
https://github.com/liam-hq/liam/pull/629/commits/47a7cdb3f4e711c978ef4e7edae945a0dfaaa1c2: ✨ Add browser back and forward support for showMode
https://github.com/liam-hq/liam/pull/629/commits/e988de9ad4039d791c7a9625ebb086a8f0ba849a: ♻️ Refactor pushState logic into a separate function to improve code clarity
We've been noticing an error in the local web version recently（when changing showMode）. 
Since it's only occurring in the local environment, I've decided to not address it for now.
ex: …
> ✨ Add browser back and forward support for showMode

- .changeset/weak-eagles-leave.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableColumnList/TableColumn/TableColumn.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableHeader/TableHeader.module.css
Rather than changing the isConnectable of each handle, the overall nodesConnectable is changed.
I think it should be changed when individual response is required in the future.
At the same time, the style of the cursor was changed.
resolve: #333
> 🐛 remove meaningless connection

- .changeset/seven-rivers-run.md
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/CopyLinkButton/CopyLinkButton.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/CopyLinkButton/CopyLinkButton.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/CopyLinkButton/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/MenuItemLink/MenuItemLink.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/MenuItemLink/MenuItemLink.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/MenuItemLink/index.ts
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableCounter/TableCounter.tsx
- frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
- frontend/packages/ui/src/icons/index.ts
- frontend/packages/ui/src/styles/variables.css
The information that was displayed on the AppBar in mobile width has been adjusted to be displayed on the LeftPane side.
N/A
N/A
**@liam-hq/cli**
| mobile | desktop |
| <video src="https://github.com/user-attachments/assets/052de265-f206-424f-8899-db6b589b72cc" /> | ![スクリーンショット 2025-01-31 11 34 48](https://github.com/user-attachments/assets/79603841-cda2-4c61-8e15-5703fbc924a2) | 
**@liam-hq/erd-web**
| mobile | desktop |
| <video src="https://github.com/user-attachments/assets/412733df-c6cf-4d9b-b436-ce04a854e3b0" /> | ![スクリーンショット 2025-01-31 11 34 27](https://github.com/user-attachments/assets/b030b634-2c20-4e79-ba4a-a21f573be887) | 
N/A
> 💄 Adjust UI of LeftPane on mobile widths

- .changeset/twenty-pigs-accept.md
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.module.css
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
🎨 Make SidebarFooter appear after scrolling when table list overflows 
Refactored Sidebar layout to allow the table list to occupy more space initially. The entire sidebar is now scrollable, and SidebarFooter is displayed only after scrolling.
before:
https://github.com/user-attachments/assets/ef4aed8b-adc0-46a9-a5fe-ac93dc22d525
after:
https://github.com/user-attachments/assets/4accbb26-2939-4a47-9229-95f834b7e88e
> 🎨 Make SidebarFooter appear after scrolling when table list overflows

- .changeset/brave-rocks-return.md
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.tsx
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/MenuItemLink/MenuItemLink.tsx
I've made adjustments to prevent the 'noreferrer' attribute from being added when linking to the same domain, while taking into account both the CLI and web versions.
ref. https://github.com/liam-hq/liam/pull/628#discussion_r1940525096
| cli ver (noreferrer) | web ver (without noreferrer) |
| ![スクリーンショット 2025-02-04 15 04 45](https://github.com/user-attachments/assets/b7a8a464-d103-415e-858a-4d259a6dfd6f) | ![スクリーンショット 2025-02-04 15 05 08](https://github.com/user-attachments/assets/609bde6a-f4d1-4be7-a8a2-860dd154ffea) |
> 🎨 Enhance MenuItemLink with improved external link handling

- .changeset/seven-chicken-jam.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.module.css
Hide Sidebar trigger on the canvas on mobile view.
Since `1` already provides the necessary functionality on mobile, `2` becomes a redundant button.
> 🎨 Hide Sidebar trigger at canvas on mobile view

- .changeset/bright-cougars-nail.md
- frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/LeftPane.module.css
The LeftPane version was slightly lower than the center. 
It has been modified to display in the vertical center.
N/A
| ![スクリーンショット 2025-02-04 17 45 23](https://github.com/user-attachments/assets/df9b1899-3483-42be-a820-310b87fa0178) | ![スクリーンショット 2025-02-04 17 45 07](https://github.com/user-attachments/assets/c59592d7-c7e1-4da3-bc2f-76b21461d40e) | 
N/A
> 💄Improve version display styling with flexbox alignment

- .changeset/spotty-berries-collect.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useAutoLayout/useAutoLayout.ts
Fixed an issue in mobile Safari where the initial auto layout was not applied. 
https://github.com/user-attachments/assets/dd726ef7-1441-4bb9-bab4-2efe911b3111
The problem was caused by executing setInitializeComplete(true) and performing layout calculations before the nodes were updated by setNodes. 
To resolve this, setInitializeComplete is now executed after setNodes has completed.
N/A
| Chrome / Mac | Safari / Mac |
| <video src="https://github.com/user-attachments/assets/7fcaa2ad-7c0e-4f2b-96b8-3b4a14a748aa" /> | <video src="https://github.com/user-attachments/assets/acd3342f-72b2-4587-a094-804c365dd9ce" /> | 
| Chrome / iPhone | Safari / iPhone |
| <video src="https://github.com/user-attachments/assets/a47ed159-7edd-4a45-ac0f-2ff00c9961bb" /> …
> 🐛 Improve ERD auto-layout rendering with state-based approach

- .changeset/fast-pugs-change.md
- frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/RelationshipEdge/RelationshipEdge.tsx
Removed a green dot on the left top when it rendered.
The green dot on the let top is an group of `ellipse` objects who are specified positive values of `begin` attributes.
The `animateMotion` element will position the object at its original coordinates (`cx`, `cy`) before the time specified in the begin attribute has elapsed. If a negative value is specified to `begin` attribute, the object is considered to have started moving before it is rendered.
I created a minimal reproduction how positive/negative `begin` values works. I hope this will help your understanding.
https://codepen.io/tnyo43/pen/vEBqNxw
resolve: https://github.com/liam-hq/liam/issues/641
- specify non-positive number to `begin` attribute of `animateMotion` of `ellipse` object to make them move from the beginning.
1. run …
> 🐛 Removed a green dot on the left top when it rendered

- frontend/packages/e2e/.gitignore
- frontend/packages/e2e/global-setup.ts
- frontend/packages/e2e/playwright.config.ts
- frontend/packages/e2e/tests/e2e/toolbar.test.ts
- frontend/packages/e2e/tests/vrt/vrt.test.ts
Add global setup for cookie acceptance in E2E tests.
> ✅ Add global setup for cookie acceptance in E2E tests

- frontend/internal-packages/agent/src/repositories/supabase.ts
- frontend/internal-packages/db/schema/schema.sql
- frontend/internal-packages/db/supabase/database.types.ts
- frontend/internal-packages/db/supabase/migrations/20250616032711_drop_old_update_building_schema.sql
I implemented two fixes to resolve 404 errors in `update_building_schema` RPC calls:
1. **Client fix**(https://github.com/liam-hq/liam/pull/2021/commits/1b9ca0d8b141558ccf72c91dbfdfc6b063956693): Removed extra `p_design_session_id` parameter from `rpcParams` to match the 6-parameter function signature (**this resolves the 404 error**)
2. **Database cleanup**(https://github.com/liam-hq/liam/pull/2021/commits/6178aced43f98048c7cad6b999b85622dd120e7b ): Added migration to drop the old 5-parameter function version (**not related to this error**, but prevents future conflicts since `supabase db squash` would likely preserve both versions)
Both the parameter mismatch and function overload issues are now resolved.
✅ Confirmed update_building_schema RPC calls are now successful. …
> fix: resolve parameter mismatch in `update_building_schema` RPC call

- renovate.json
- N/A
To improve dependency management efficiency by automatically merging development tool updates that only need CI to pass.
- The list of packages included in the `dev-tools` automerge group
- Whether any critical build tools were inadvertently included (vite packages have been intentionally excluded)
The JSON file has been validated and follows the existing Renovate configuration patterns.
pr_agent:walkthrough
- Added a new `dev-tools` automerge group for development dependencies that only need CI to pass
- Consolidated the langfuse packages into the internal packages automerge rule since they're used by internal packages
> ⚙️(renovate): Add dev-tools automerge group

- .coderabbit.yaml
- resolve: 
CodeRabbit's high-level summaries were enabled by default, but they may not be needed for our workflow. This change disables the high-level summary feature to streamline the review process and reduce noise in PR reviews.
> 🔧 Update CodeRabbit configuration to disable high-level summaries

- frontend/internal-packages/agent/src/deepModeling.test.ts
- frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
- resolve:
There was a minor oversight in this pull request.
- https://github.com/liam-hq/liam/pull/2520
The design agent was failing with a validation error: **Failed to parse design agent response: ValiError: Invalid key: Expected "operations" but received undefined**
This occurred because there was a mismatch between the prompt template and the response schema:
- The prompt instructed the LLM to return schema changes in a field called "schemaChanges"
- But the parsing code expected the field to be named "operations"
This change updates the prompt template to use "operations" consistently, aligning it with the expected response schema and resolving the parsing failures.
I have confirmed that the error has been resolved in my local environment.
（Sometimes it fails with another error.）
> fix: correct field name mismatch in design agent response schema

- frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteContent/CommandPaletteContent.module.css
~resolve:~
- fix for https://github.com/liam-hq/liam/pull/2014
To make it look prettier, I added border-radius.
|before|after|
|--|--|
|<img width="914" height="198" alt="Screenshot 0007-07-12 at 10 04 18" src="https://github.com/user-attachments/assets/b65927f6-f0f6-4dbb-9023-53ff18a1f309" />|<img width="914" height="198" alt="Screenshot 0007-07-12 at 10 04 12" src="https://github.com/user-attachments/assets/94a17c81-cd24-4b3d-9361-da34161e3f8e" />|
> 💄 style(command palette): set border-radius of option

- frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
- resolve:
The database schema build agent prompts incorrectly referenced a 'primary' property in column definitions, but this property doesn't exist in the actual column schema.
https://github.com/liam-hq/liam/blob/434b169c169b0fe597b47b8172949bb68fc9cd22/frontend/packages/db-structure/src/schema/schema.ts#L20-L27
Primary keys should only be defined through the constraints object using `primaryKeyConstraintSchema`, not as a column property. This mismatch could lead to confusion and incorrect schema generation attempts by the agent.
This change:
- Removes all references to the non-existent 'primary' column property
- Updates examples to show proper primary key definition via constraints
- Aligns the prompts with the actual schema structure …
> fix: remove non-existent 'primary' property references from database schema prompts

- frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
- resolve:
The design agent was generating JSON patch operations in incorrect order, causing `OPERATION_PATH_UNRESOLVABLE` errors. Specifically, the LLM was attempting to add constraints to non-existent tables or modify properties before creating the required parent structures.
This change improves the prompt to:
- Emphasize that "add" operations must come before "replace" or "remove" operations
- Require all table properties (columns, constraints, indexes) to be included in the initial table creation
- Prohibit separate constraint additions that should be part of the table definition
- Provide clear examples of correct vs incorrect operation sequences
This prevents the root cause of path resolution errors by ensuring the LLM generates logically ordered and complete operations.
🚧 More …
> PR1: fix: improve design agent prompt to prevent invalid JSON patch operations

- frontend/internal-packages/agent/eslint-suppressions.json
- frontend/internal-packages/agent/src/repositories/supabase.test.ts
- frontend/internal-packages/agent/src/repositories/supabase.ts
- frontend/internal-packages/agent/src/utils/pathPreparation.ts
- resolve:
JSON patch operations were failing with "OPERATION_PATH_UNRESOLVABLE" errors when trying to modify paths that don't exist in the schema structure. For example, operations like `{"op": "replace", "path": "/tables/users/columns/id/primary", "value": true}` would fail when the `users` table or its nested structure didn't exist.
This change adds defensive path structure creation before applying patch operations:
- The `ensurePathStructure` function pre-creates necessary nested objects for patch paths
- The test is written below
- https://github.com/liam-hq/liam/pull/2559/files#diff-837c19dcb5c19550a524cfc2cedf0d2124698a749333d23eaf08fddcb2c26ce4
- It handles both schema restoration from version history and new patch applications
- This prevents crashes while maintaining the logical …
> PR2: fix: prevent OPERATION_PATH_UNRESOLVABLE errors in JSON patch operations

- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.test.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.test.ts
- frontend/internal-packages/agent/src/deepModeling.test.ts
- frontend/internal-packages/agent/src/repositories/supabase.ts
- frontend/internal-packages/agent/src/repositories/types.ts
https://github.com/liam-hq/liam/pull/2571#discussion_r2209166494
The function name `createEmptyVersion` was not descriptive enough about its purpose. The function specifically creates empty patch versions (where patch/reverse_patch are null) as part of the schema versioning system. Renaming it to `createEmptyPatchVersion` makes the intent clearer and improves code readability.
- Renamed function from `createEmptyVersion` to `createEmptyPatchVersion`
- Updated corresponding type from `CreateEmptyVersionParams` to `CreateEmptyPatchVersionParams`
- Updated all function calls across the agent module
- Updated test mocks and assertions
- Updated imports in affected files
- `repositories/types.ts` - Updated type definitions and interface
- `repositories/supabase.ts` - Updated implementation and …
> ♻️ Rename createEmptyVersion to createEmptyPatchVersion

- .github/scripts/setup-claude.sh
- .github/workflows/claude-pr-creator.yml
- .github/workflows/claude.yml
- resolve:
This change ensures Claude Code Action can successfully complete tasks across multiple packages in our monorepo by enforcing lint and format checks before committing.
This prevents CI failures from unresolved lint errors and enables Claude to iterate and fix issues autonomously.
- .github/workflows/claude.yml
- .github/workflows/claude-pr-creator.yml
When requesting a task with `@claude` and when running claude at night with the issue label https://github.com/liam-hq/liam/labels/scheduled-task.
I tested the changes by forking the repository in my personal account:
https://github.com/FunamaYukina/liam
Here are the results of the verification:
While the issue descriptions could be refined a bit further, the workflow is now able to handle changes that span across multiple packages …
> feat: Implement automated lint and format checks for Claude Code Actions

- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.module.css
- resolve:
When VersionMessage component displays long paths, the text doesn't wrap and overflows horizontally, breaking the UI layout.
This fix ensures that long paths wrap properly within the container. The arrow icons (→) are also handled correctly with the wrapping, improving  readability.
| ------ | ----- |
| ![スクリーンショット 2025-07-17 18 25 20](https://github.com/user-attachments/assets/abe9c4d1-a6df-49c8-8630-2d3ccc283647) | ![スクリーンショット 2025-07-18 11 27 35](https://github.com/user-attachments/assets/d8b8fb68-ac16-4f51-8d87-84fb7fdab10f) |
> 💄 Fix long text wrapping in VersionMessage component

- frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/VersionDropdown.tsx
- resolve:
This change updates the version dropdown option labels from "vXX" to "Version XX" format to increase the clickable area and improve usability.
- Before: v1, v2, v3...
- After: Version 1, Version 2, Version 3...
By expanding the text in dropdown menu items, users have a larger clickable area. The trigger button remains as "vXX" to maintain a compact appearance.
preview: https://liam-app-git-feature-version-dropdown-label-update-liambx.vercel.app/app/design_sessions/445655f9-f87d-4da0-ae4e-7e74ef55a4fc
> 💄 Update version dropdown option labels for better usability

- frontend/internal-packages/agent/src/chat/workflow/utils/withTimelineItemSync.test.ts
- frontend/internal-packages/agent/src/chat/workflow/utils/withTimelineItemSync.ts
- frontend/internal-packages/agent/src/db-agent/nodes/invokeSchemaDesignToolNode.ts
- resolve: Add timeline synchronization for ToolNode message execution
This change enables timeline synchronization for ToolNode messages in the agent workflow, ensuring that tool execution results (both successful and error responses) are properly tracked and displayed in the timeline UI. Previously, ToolNode executions were not being saved to the timeline_items table, making it difficult to track the complete workflow execution history.
Key improvements:
- Extends `withTimelineItemSync` to handle `ToolMessage` instances
- Adds automatic error detection (messages containing "error" are saved as 'error' type)
- Updates `invokeSchemaDesignToolNode` to sync all tool messages to timeline
- Refactors `withTimelineItemSync` to reduce complexity by extracting helper functions
- Ensures proper …
> ✨ Add timeline sync support for ToolNode messages

- frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.module.css
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.tsx
- resolve:
When the same agent sends multiple consecutive messages, each message was displaying the avatar and name, making the UI repetitive and cluttered. This change improves readability by showing the avatar and name only on the first message in a consecutive group.
preview: https://liam-app-git-feature-bundle-consecutive-posts-liambx.vercel.app/app/design_sessions/c21ee010-e456-47c7-9570-6d18624d9771
https://github.com/user-attachments/assets/844b0eb0-095d-42b1-b8fe-f4d118fe9f92
> feat: Bundle consecutive messages from the same agent

- frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/MigrationsViewer/useMigrationsViewer/editorTheme.ts
- frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/MigrationsViewer/useMigrationsViewer/useMigrationsViewer.tsx
- resolve:
This PR improves the fold gutter markers in the Schema Updates viewer:
1. **Visual consistency**: Replaces default CodeMirror text characters with Chevron icons from our UI library to match our
design system
2. **Memory leak fix**: The initial React implementation using `createRoot()` caused memory leaks when fold markers were
created/destroyed. This has been fixed by using direct DOM manipulation while maintaining the same visual appearance
The implementation now creates SVG icons directly with the same styling as our lucide-react icons (stroke-width: 1.5).
|        | Open | Close |
|--------|--------------------|--------------------|
| **Before** | ![スクリーンショット 2025-07-23 21:06:55](https://github.com/user-attachments/assets/3babdfe0-1705-4223-bad5-7c27515c3af3) | ![スクリーンショット …
> 💄 Improve fold gutter markers with Chevron icons and fix memory leak

- frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts
- frontend/internal-packages/agent/src/langchain/agents/pmAnalysisAgent/agent.ts
- resolve: N/A
This change adds logging for AI reasoning summaries in the analyze requirements node. When the PM Analysis Agent generates reasoning summaries, they are now logged as assistant messages before the main analysis result, providing better transparency into the AI's decision-making process.
> ✨ Add reasoning summary logging in analyze requirements node

- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
- frontend/internal-packages/agent/src/chat/workflow/nodes/generateUsecaseNode.ts
- frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/agent.ts
- frontend/internal-packages/agent/src/langchain/agents/pmAnalysisAgent/agent.ts
- frontend/internal-packages/agent/src/langchain/agents/qaGenerateUsecaseAgent/agent.ts
- frontend/internal-packages/agent/src/langchain/utils/schema.ts
- frontend/internal-packages/agent/src/langchain/utils/types.ts
- resolve: N/A
- Related to: #2730
This change extends the reasoning output functionality implemented in #2730 for `analyzeRequirementsNode` to the `databaseSchemaBuildAgent`. This is part of a broader effort to add reasoning transparency across all AI agents in the system, providing better visibility into the decision-making process.
Following the pattern established in #2730 for the PM Analysis Agent:
- Added reasoning response structure to `invokeDesignAgent` similar to `PMAnalysisAgent`
- Updated `designSchemaNode` to log reasoning summaries via `logAssistantMessage`
- Modified return type to include both response and reasoning fields
- Updated all related tests to handle the new response structure
This ensures consistency across all agents and provides users with insights into how …
> ✨ Add reasoning output support to databaseSchemaBuildAgent

- frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.stories.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.tsx
- frontend/apps/app/components/SessionDetailPage/types.ts
- resolve: #
When users click the "View" button on a version message in the chat, the selected version should be updated to display the corresponding schema. This change connects the VersionMessage component's onView callback to the SessionDetailPageClient's handleChangeSelectedVersion function to enable version switching functionality.
https://github.com/user-attachments/assets/760e5fcb-3573-4d05-9755-c0bce24f63ce
> ✨ Connect VersionMessage onView to version selection handler

- frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
- frontend/apps/app/components/SessionDetailPage/components/Output/Output.tsx
- frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/SchemaUpdates.module.css
- frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/SchemaUpdates.tsx
- resolve: N/A
This PR removes the quick fix functionality and review comment UI toggle button from the schema updates view. The quick fix feature with the `onQuickFix` handler was not being used effectively, and the UI toggle for showing/hiding review comments added unnecessary complexity to the interface.
The changes simplify the component hierarchy by removing unused props and state management, resulting in cleaner and more maintainable code.
| <img width="1129" height="992" alt="スクリーンショット 2025-07-29 19 15 33" src="https://github.com/user-attachments/assets/5dda4667-56d6-49bb-8602-3432256637f9" /> | <img width="1130" height="994" alt="スクリーンショット 2025-07-29 19 14 29" src="https://github.com/user-attachments/assets/b6e2cb97-2729-4b04-bbb9-1c746a3150bf …
> 🔥 Remove quick fix functionality and review comment UI toggle

- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.module.css
- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.tsx
- resolve: N/A
When the diff indicator is displayed on a table column, the cardinality indicator (left handle) overlaps with the diff box. This fix adjusts the handle position from -20px to -56px to accommodate the 36px diff box width, ensuring proper visibility of both UI elements.
**Liam DB**
| All fields | Table name | Key only |
|--------|--------|--------|
| <img width="1685" height="994" alt="スクリーンショット 2025-07-30 11 18 40" src="https://github.com/user-attachments/assets/4bc81c5c-e0ed-4281-a197-3619e1b7fb11" /> | <img width="1686" height="994" alt="スクリーンショット 2025-07-30 11 18 58" src="https://github.com/user-attachments/assets/35528fde-9004-4895-88d1-7afe8ae94a78" /> | <img width="1684" height="993" alt="スクリーンショット 2025-07-30 11 19 12" …
> 🐛 Fix cardinality indicator position when diff is shown

- frontend/packages/db-structure/src/diff/buildSchemaDiff.ts
- frontend/packages/db-structure/src/diff/columns/buildColumnTypeDiffItem.ts
- frontend/packages/db-structure/src/diff/types.ts
- frontend/packages/db-structure/src/schema/index.ts
- frontend/packages/db-structure/src/schema/schema.ts
- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/Columns.tsx
- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.tsx
- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/ColumnsItem/getChangeStatus.ts
- frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/TableDetail.tsx
- resolve: N/A
This PR adds diff highlighting functionality to the Columns component within TableDetail, enabling visual indication of column changes (added, removed, modified) when viewing schema differences.
The implementation follows the same pattern established in the Head and Comment components, using the shared `useDiffStyle` hook for consistent styling across all TableDetail sections.
- Pass entire `table` object to `Columns` component instead of separate props for better data flow
- Add `getChangeStatus` utility to determine column change status based on diff items
- Integrate diff highlighting into `ColumnsItem` component using the shared `useDiffStyle` hook
- Maintain consistency with existing diff highlighting patterns in TableDetail
- Add support for detecting and highlighting …
> ✨ add diff highlighting to TableDetail Columns component

- frontend/apps/app/app/app/public/design_sessions/[id]/page.tsx
- frontend/apps/app/components/PublicLayout/PublicAppBar/PublicAppBar.module.css
- frontend/apps/app/components/PublicLayout/PublicAppBar/PublicAppBar.tsx
- frontend/apps/app/components/PublicLayout/PublicAppBar/index.ts
- frontend/apps/app/components/PublicLayout/PublicGlobalNav/PublicGlobalNav.module.css
- frontend/apps/app/components/PublicLayout/PublicGlobalNav/PublicGlobalNav.tsx
- frontend/apps/app/components/PublicLayout/PublicGlobalNav/index.ts
- frontend/apps/app/components/PublicLayout/PublicLayout.module.css
- frontend/apps/app/components/PublicLayout/PublicLayout.tsx
- frontend/apps/app/components/PublicLayout/index.ts
- frontend/apps/app/components/PublicSessionDetailPage/PublicSessionDetailPage.module.css
- frontend/apps/app/components/PublicSessionDetailPage/PublicSessionDetailPage.tsx
- frontend/apps/app/components/PublicSessionDetailPage/index.ts
- frontend/apps/app/components/SessionDetailPage/components/Output/components/Artifact/hooks/useRealtimeArtifact.ts
- frontend/apps/app/components/ShareDialog/ShareDialog.tsx
- frontend/apps/app/libs/routes/constants.ts
- frontend/apps/app/libs/routes/index.ts
- frontend/apps/app/libs/routes/routeDefinitions.ts
- frontend/apps/app/middleware.ts
- frontend/apps/app/next.config.ts
- resolve: https://github.com/route06/liam-internal/issues/5370
This implements Phase 1.4 of the Public Share feature, adding public session pages with anonymous access. The implementation follows a Server-Only design pattern where all Supabase access goes through the server, leveraging RLS policies for secure anonymous data access.
1. **Public Session Page Implementation**
- Added public route at `/app/public/design_sessions/[id]` with Server Component architecture
- Implemented `createPublicServerClient` for anonymous Supabase access
- Added proper 404 handling for non-public sessions
- Enabled ISR with 60-second revalidation for optimal performance
2. **Public Layout Components**
- Created `PublicLayout` with simplified navigation for public views
- Added `PublicGlobalNav` with Liam …
> feat: Add public view UI components and cache optimization

- frontend/packages/pglite-server/src/PGliteInstanceManager.ts
- frontend/packages/schema/src/parser/sql/postgresql/parser.ts
- resolve: https://github.com/route06/liam-internal/issues/5450
This PR fixes memory allocation issues in both pg-query-emscripten (SQL parser) and PGlite (SQL execution engine) that were causing CI failures during the Deep Modeling process.
1. **pg-query-emscripten**: Default WebAssembly memory was insufficient for parsing large SQL statements, causing "memory access out of bounds" errors
2. **PGlite**: Even after PR #3092 increased memory to 256MB, it was still insufficient for Deep Modeling's complex SQL operations
1. **pg-query-emscripten**: Added explicit WebAssembly.Memory configuration with 128MB initial allocation
2. **PGlite**: Increased initial memory from 256MB to 2GB to handle large-scale SQL statements
- pg-query-emscripten and PGlite are separate WebAssembly instances with …
> 🐛(pglite): Fix memory configuration for pg-query-emscripten and PGlite

- frontend/apps/app/package.json
- frontend/internal-packages/agent/src/lead-agent/classifyMessage/index.ts
- frontend/internal-packages/agent/src/pm-agent/invokePmAnalysisAgent.ts
- pnpm-lock.yaml
- N/A (no tracked issue)
This pull request **adds native streaming support for `leadAgent`**.  
It builds directly on the functionality introduced in **[PR #3121](https://github.com/liam-hq/liam/pull/3121)**—already merged into `main`—by making that implementation streaming-compatible.
> **Commits:** All commits in this PR relate exclusively to the new streaming logic.
- **Real-time UX** – Streaming delivers incremental tokens, reducing perceived latency and aligning `leadAgent` with our other agents.  
- **Feature parity with #3121** – The work in #3121 handled only non-streaming paths; this PR completes the feature set.
> ✨ Add Streaming Support to `leadAgent`

- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/AiMessage.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/ToolCalls/ToolCalls.module.css
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/ToolCalls/ToolCalls.tsx
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/schema.ts
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/utils/extractReasoningFromMessage.ts
- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/utils/extractToolCallsFromMessage.ts
- resolve: N/A
This PR extracts tool call information from AI messages and improves the display of tool calls in the chat interface. The changes separate schema definitions into a shared module and create a dedicated utility for extracting tool calls, making the codebase more maintainable and type-safe.
1. **Schema extraction**: Moved message parsing schemas to a shared `schema.ts` file
2. **Tool calls utility**: Created `extractToolCallsFromMessage` utility for parsing tool calls from messages
3. **Type safety**: Defined `ToolCalls` type for better type safety across components
4. **UI improvements**: Simplified the ToolCalls component with cleaner styling and layout
5. **Conditional rendering**: Response messages now only render when content exists
- Uses Valibot for runtime type …
> ✨ Add tool calls extraction for AI message display

- frontend/apps/app/components/SessionDetailPage/components/Chat/components/Messages/AiMessage/AiMessage.tsx
- frontend/apps/app/components/SessionDetailPage/hooks/useStream/useStream.ts
- resolve: N/A
This PR fixes two issues in the AiMessage component:
1. **Agent name parsing bug**: The `getAgentInfo` function was incorrectly returning DB Agent for all agent types due to a logic error
2. **Lead Agent support**: Added support for the new Lead Agent role in the streaming messages
- Fixed message state preservation during streaming updates to maintain agent name and other properties
- Extended `agentRoleSchema` to include 'lead' role
- Added temporary Lead Agent display (currently using QA Agent avatar with TODO for dedicated component)
- Cleaned up unused Database type import
The streaming update was replacing the entire message object instead of merging, which caused the agent name to be lost and default to DB Agent. This has been fixed by properly merging the incoming …
> 🐛 Fix agent name parsing and Lead Agent support in AiMessage

- frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
- frontend/apps/app/components/SessionDetailPage/hooks/useStream/MessageTupleManager.ts
- frontend/internal-packages/agent/src/db-agent/invokeDesignAgent.ts
- frontend/internal-packages/agent/src/lead-agent/classifyMessage/index.ts
- frontend/internal-packages/agent/src/lead-agent/summarizeWorkflow/index.ts
- frontend/internal-packages/agent/src/lead-agent/tools/routeToAgent.ts
- frontend/internal-packages/agent/src/pm-agent/invokePmAnalysisAgent.ts
- frontend/internal-packages/agent/src/pm-agent/tools/saveRequirementsToArtifactTool.ts
- frontend/internal-packages/agent/src/qa-agent/tools/saveTestcasesAndDmlTool.ts
- resolve: N/A
ToolMessage instances were not being properly converted to ToolMessageChunk during streaming, causing them to be excluded from the chat UI. This affected the display of tool execution results in real-time chat interactions.
| Streaming | Reload |
| <img width="1691" height="993" alt="スクリーンショット 2025-09-01 21 55 57" src="https://github.com/user-attachments/assets/bbf55625-b249-45ae-938c-f1040156d828" /> | <img width="1689" height="997" alt="スクリーンショット 2025-09-01 21 56 21" src="https://github.com/user-attachments/assets/b12181db-3584-45ab-b08e-e7e158fd5394" /> | 
This PR fixes the handling of ToolMessage in the streaming chat implementation:
1. **MessageTupleManager enhancement**: Added special handling for ToolMessage to manually convert it to …
> 🐛 Fix ToolMessage streaming in chat UI

- frontend/apps/app/components/SessionDetailPage/components/OutputPlaceholder/OutputPlaceholder.tsx
- resolve: Fix undefined baseUrl in Vercel preview environment for Rive asset loading https://github.com/route06/liam-internal/issues/5207
The OutputPlaceholder component was attempting to construct full URLs for the Rive animation asset using environment variables, which caused issues in Vercel preview environments where VERCEL_URL and VERCEL_BRANCH_URL are not accessible on the client-side.
The solution was to simplify the approach by using a relative path `/assets/loading_jack.riv` instead of constructing full URLs with environment-specific logic. This change:
- Removes complex environment variable handling that wasn't working reliably
- Uses a simple relative path that works across all environments (local, preview, production)
- Eliminates the undefined URL issue in Vercel preview …
> 🐛 Fix Vercel preview environment baseUrl undefined issue

- frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/useRealtimeVersionsWithSchema.ts
- resolve: #
When versions are updated through realtime subscriptions in the SessionDetailPage, the active tab unexpectedly resets to the ERD tab, disrupting the user's workflow. This caused two specific issues:
1. **SQL tab becomes unclickable**: When users tried to switch to the SQL tab, it would immediately revert back to the ERD tab
2. **Tab selection not preserved**: Any manual tab selection by the user would be lost when versions were updated via realtime
This occurred because the `onChangeSelectedVersion` callback was being triggered for any version update, not just when new versions are added.
The fix ensures that the ERD tab is only automatically activated when:
1. A new version is added via realtime updates
2. The user manually selects a different version
This preserves the …
> 🐛 Fix tab reset issue when versions update via realtime
